package com.indraacademy.ias_management.service;

import com.indraacademy.ias_management.entity.Leave;
import com.indraacademy.ias_management.entity.LeaveStatus;
import com.indraacademy.ias_management.repository.LeaveRepository;
import com.indraacademy.ias_management.util.SecurityUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Collections;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.Optional;

@Service
public class LeaveService {

    private static final Logger log = LoggerFactory.getLogger(LeaveService.class);
    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    @Autowired private LeaveRepository leaveRepository;
    @Autowired private NotificationService notificationService;
    @Autowired private AuditService auditService;
    @Autowired private SecurityUtil securityUtil;
    @Autowired private ObjectMapper objectMapper;

    @Transactional
    public void applyLeave(Leave leave, HttpServletRequest request){

        if (leave == null || leave.getStudentId() == null || leave.getLeaveDate() == null) {
            throw new IllegalArgumentException("Leave object and required fields must not be null.");
        }

        try {
            leave.setAppliedDate(LocalDateTime.now());
            Leave savedLeave = leaveRepository.save(leave);

            // Audit
            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "APPLY_LEAVE",
                    "Leave",
                    String.valueOf(savedLeave.getId()),
                    null,
                    objectMapper.writeValueAsString(savedLeave),
                    request.getRemoteAddr()
            );

            String studentMessage = String.format(
                    "Your leave application for %s has been submitted.",
                    savedLeave.getLeaveDate()
            );

            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Applied",
                    studentMessage,
                    "Leave Applied",
                    savedLeave.getStudentId(),
                    "Leave",
                    String.valueOf(savedLeave.getId())
            );

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not apply leave", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public void deleteLeave(String studentId,
                            String leaveDate,
                            HttpServletRequest request) {

        if (studentId == null || studentId.trim().isEmpty()
                || leaveDate == null || leaveDate.trim().isEmpty()) {
            throw new IllegalArgumentException("Student ID and leave date must be provided.");
        }

        try {
            Leave leave = leaveRepository.findByStudentIdAndLeaveDate(studentId, leaveDate);

            if (leave == null) {
                throw new IllegalArgumentException("Leave not found for student " + studentId);
            }

            if (LeaveStatus.APPROVED.equals(leave.getStatus())) {
                throw new IllegalArgumentException("Cannot delete an approved leave application.");
            }

            String oldValue = objectMapper.writeValueAsString(leave);
            String leaveIdString = String.valueOf(leave.getId());

            leaveRepository.deleteByStudentIdAndLeaveDate(studentId, leaveDate);

            // Audit
            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "DELETE_LEAVE",
                    "Leave",
                    leaveIdString,
                    oldValue,
                    null,
                    request.getRemoteAddr()
            );

            String studentMessage = String.format(
                    "Your leave application for %s has been deleted.",
                    leave.getLeaveDate()
            );

            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Cancelled",
                    studentMessage,
                    "Leave Deleted",
                    leave.getStudentId(),
                    "Leave",
                    leaveIdString
            );

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not delete leave", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public void deleteLeaveById(Long leaveId,
                                HttpServletRequest request) {

        if (leaveId == null) {
            throw new IllegalArgumentException("Leave ID must be provided.");
        }

        try {
            Leave leave = leaveRepository.findById(leaveId)
                    .orElseThrow(() -> new IllegalArgumentException("Leave not found with ID " + leaveId));

            String oldValue = objectMapper.writeValueAsString(leave);

            leaveRepository.deleteById(leaveId);

            // Audit
            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "DELETE_LEAVE_BY_ID",
                    "Leave",
                    String.valueOf(leaveId),
                    oldValue,
                    null,
                    request.getRemoteAddr()
            );

            String studentMessage = String.format(
                    "Your leave application for %s has been deleted.",
                    leave.getLeaveDate()
            );

            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Application Cancelled",
                    studentMessage,
                    "Leave_Cancelled_Student",
                    leave.getStudentId(),
                    "Leave",
                    String.valueOf(leave.getId())
            );

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not delete leave", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    public Optional<Leave> getLeaveById(Long leaveId) {
        if (leaveId == null) {
            log.warn("Attempted to get leave with null ID.");
            return Optional.empty();
        }
        log.info("Fetching leave by ID: {}", leaveId);
        try {
            return leaveRepository.findById(leaveId);
        } catch (DataAccessException e) {
            log.error("Data access error fetching leave ID: {}", leaveId, e);
            throw new RuntimeException("Could not retrieve leave due to data access issue", e);
        }
    }

    @Transactional
    public Leave updateLeaveStatus(Long leaveId, LeaveStatus status, HttpServletRequest request) {

        if (leaveId == null) {
            throw new IllegalArgumentException("Leave ID must be provided.");
        }
        if (status == null) {
            throw new IllegalArgumentException("Status must be provided.");
        }

        try {
            Leave leave = leaveRepository.findById(leaveId)
                    .orElseThrow(() -> new NoSuchElementException("Leave not found with ID " + leaveId));

            String oldValue = objectMapper.writeValueAsString(leave);
            leave.setStatus(status);
            Leave updated = leaveRepository.save(leave);

            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "UPDATE_LEAVE_STATUS",
                    "Leave",
                    String.valueOf(leaveId),
                    oldValue,
                    objectMapper.writeValueAsString(updated),
                    request.getRemoteAddr()
            );

            String studentMessage = String.format(
                    "Your leave application for %s has been %s.",
                    updated.getLeaveDate(),
                    status.name().toLowerCase()
            );

            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Status Updated",
                    studentMessage,
                    "Leave_Status_" + status.name(),
                    updated.getStudentId(),
                    "Leave",
                    String.valueOf(updated.getId())
            );

            return updated;

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not update leave status", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    public Page<Leave> getLeavesFiltered(String className, String studentId, String date, Pageable pageable) {
        log.info("Filtering leaves. Class: {}, Student ID: {}, Date: {}", className, studentId, date);
        try {
            if (className != null && studentId != null && date != null) {
                return leaveRepository.findByClassNameAndStudentIdContainingAndLeaveDate(className, studentId, date, pageable);
            } else if (className != null && studentId != null) {
                return leaveRepository.findByClassNameAndStudentIdContaining(className, studentId, pageable);
            } else if (className != null && date != null) {
                return leaveRepository.findByClassNameAndLeaveDate(className, date, pageable);
            } else if (studentId != null && date != null) {
                return leaveRepository.findByStudentIdContainingAndLeaveDate(studentId, date, pageable);
            } else if (className != null) {
                return leaveRepository.findByClassName(className, pageable);
            } else if (studentId != null) {
                return leaveRepository.findByStudentIdContaining(studentId, pageable);
            } else if (date != null) {
                return leaveRepository.findByLeaveDate(date, pageable);
            } else {
                return leaveRepository.findAll(pageable);
            }
        } catch (DataAccessException e) {
            log.error("Data access error during getLeavesFiltered. Class: {}, Student ID: {}, Date: {}", className, studentId, date, e);
            throw new RuntimeException("Could not retrieve filtered leaves due to data access issue", e);
        }
    }

    public Page<Leave> getLeavesByStudentId(String studentId, Pageable pageable) {
        if (studentId == null || studentId.trim().isEmpty()) {
            log.warn("Attempted to get leaves with null/empty student ID.");
            return Page.empty(pageable);
        }
        log.info("Fetching leaves for student ID: {}", studentId);
        try {
            return leaveRepository.findByStudentId(studentId, pageable);
        } catch (DataAccessException e) {
            log.error("Data access error fetching leaves for student ID: {}", studentId, e);
            throw new RuntimeException("Could not retrieve leaves by student ID due to data access issue", e);
        }
    }

    public List<String> getLeavesByDateAndClass(String date, String className) {
        if (date == null || date.trim().isEmpty() || className == null || className.trim().isEmpty()) {
            log.warn("Attempted to get leaves by date/class with null/empty parameters. Date: {}, Class: {}", date, className);
            return Collections.emptyList();
        }
        log.info("Fetching leave student IDs for date: {} and class: {}", date, className);
        try {
            return leaveRepository.findByLeaveDateAndClassName(date, className);
        } catch (DataAccessException e) {
            log.error("Data access error fetching leaves by date {} and class {}", date, className, e);
            throw new RuntimeException("Could not retrieve leaves due to data access issue", e);
        }
    }
}