package com.indraacademy.ias_management.service;

import com.indraacademy.ias_management.entity.Leave;
import com.indraacademy.ias_management.repository.LeaveRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Optional;

@Service
public class LeaveService {

    @Autowired private LeaveRepository leaveRepository;
    @Autowired private NotificationService notificationService;

    private static final DateTimeFormatter DATE_FORMATTER = DateTimeFormatter.ofPattern("dd-MM-yyyy");

    public void applyLeave(Leave leave){
        leave.setAppliedDate(LocalDateTime.now());
        leaveRepository.save(leave);

        String studentMessage = String.format("Your leave application for %s has been submitted.", leave.getLeaveDate());
        notificationService.createAutoGeneratedIndividualNotification(
                "Leave Application Submitted", // Title
                studentMessage,              // Message
                "Leave Application Submitted",     // Type
                leave.getStudentId(),                   // User ID of the student
                "Leave",                     // relatedEntityType
                leave.getId()                // relatedEntityId (Long)
        );
    }

    @Transactional
    public void deleteLeave(String studentId, String leaveDate) {
        Leave leave = leaveRepository.findByStudentIdAndLeaveDate(studentId, leaveDate);
        if (leave != null) {
            leaveRepository.deleteByStudentIdAndLeaveDate(studentId, leaveDate);
            String studentMessage = String.format("Your leave application for %s has been deleted.", leave.getLeaveDate());
            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Application Cancelled",
                    studentMessage,
                    "Leave Application Deleted",
                    leave.getStudentId(),
                    "Leave",
                    leave.getId()
            );
        } else {
            throw new IllegalArgumentException("Leave not found for student " + studentId + " on date " + leaveDate);
        }
    }

    @Transactional
    public void deleteLeaveById(String leaveId) {
        leaveRepository.deleteById(leaveId);
        Optional<Leave> optionalLeave = leaveRepository.findById(leaveId);
        if (optionalLeave.isPresent()) {
            Leave leave = optionalLeave.get();
            leaveRepository.delete(leave);
            String studentMessage = String.format("Your leave application for %s has been deleted.", leave.getLeaveDate());
            notificationService.createAutoGeneratedIndividualNotification(
                    "Leave Application Cancelled",
                    studentMessage,
                    "Leave_Cancelled_Student",
                    leave.getStudentId(),
                    "Leave",
                    leave.getId()
            );
        } else {
            throw new IllegalArgumentException("Leave with ID " + leaveId + " not found.");
        }
    }

    public Optional<Leave> getLeaveById(String leaveId) {
        return leaveRepository.findById(leaveId);
    }

    public Page<Leave> getLeavesFiltered(String className, String studentId, String date, Pageable pageable) {
        if (className != null && studentId != null && date != null) {
            return leaveRepository.findByClassNameAndStudentIdContainingAndLeaveDate(className, studentId, date, pageable);
        } else if (className != null && studentId != null) {
            return leaveRepository.findByClassNameAndStudentIdContaining(className, studentId, pageable);
        } else if (className != null && date != null) {
            return leaveRepository.findByClassNameAndLeaveDate(className, date, pageable);
        } else if (studentId != null && date != null) {
            return leaveRepository.findByStudentIdContainingAndLeaveDate(studentId, date, pageable);
        } else if (className != null) {
            return leaveRepository.findByClassName(className, pageable);
        } else if (studentId != null) {
            return leaveRepository.findByStudentIdContaining(studentId, pageable);
        } else if (date != null) {
            return leaveRepository.findByLeaveDate(date, pageable);
        } else {
            return leaveRepository.findAll(pageable);
        }
    }

    public Page<Leave> getLeavesByStudentId(String studentId, Pageable pageable) {
        return leaveRepository.findByStudentId(studentId, pageable);
    }

    public List<String> getLeavesByDateAndClass(String date, String className) {
        return leaveRepository.findByLeaveDateAndClassName(date, className);
    }
}