package com.indraacademy.ias_management.service;

import com.indraacademy.ias_management.dto.UserNotificationDTO;
import com.indraacademy.ias_management.entity.Notification;
import com.indraacademy.ias_management.entity.UserNotification;
import com.indraacademy.ias_management.repository.NotificationRepository;
import com.indraacademy.ias_management.repository.UserNotificationRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class NotificationService {

    @Autowired private AuthService authService;
    @Autowired private NotificationRepository notificationRepository;
    @Autowired private UserNotificationRepository userNotificationRepository;

    @Transactional
    public Notification createBroadNotification(Notification notification, String authorizationHeader) {
        notification.setCreatedBy(authService.getUserIdFromToken(authorizationHeader));
        notification.setCreatedAt(LocalDateTime.now());
        return notificationRepository.save(notification);
    }

    @Transactional
    public UserNotification createAutoGeneratedIndividualNotification(
            String title, String message, String type, String userId,
            String relatedEntityType, Long relatedEntityId) {

        Notification notification = new Notification();
        notification.setTitle(title);
        notification.setMessage(message);
        notification.setType(type);
        notification.setAudience(null); // Explicitly setting audience to null for personalized
        notification.setCreatedAt(LocalDateTime.now());
        Notification savedNotification = notificationRepository.save(notification);

        UserNotification userNotification = new UserNotification();
        userNotification.setUserId(userId);
        userNotification.setNotification(savedNotification);
        userNotification.setIsRead(false);
        userNotification.setCreatedAt(LocalDateTime.now());
        return userNotificationRepository.save(userNotification);
    }


    @Transactional
    public List<UserNotificationDTO> getNotificationsForUser(String userId, String userRole) {
        List<UserNotification> userNotifications = new ArrayList<>(userNotificationRepository.findByUserIdOrderByCreatedAtDesc(userId));

        List<Notification> broadNotifications = notificationRepository.findAll().stream()
                .filter(notification -> {
                    String audience = notification.getAudience();
                    if (audience == null) return false;

                    return switch (audience) {
                        case "ALL" -> true;
                        case "STUDENTS" -> "STUDENT".equals(userRole);
                        case "TEACHERS" -> "TEACHER".equals(userRole);
                        default -> false;
                    };
                })
                .toList();

        for (Notification broadNotif : broadNotifications) {
            if (!userNotificationRepository.existsByUserIdAndNotificationId(userId, broadNotif.getId())) {
                UserNotification newUserNotif = new UserNotification();
                newUserNotif.setUserId(userId);
                newUserNotif.setNotification(broadNotif);
                newUserNotif.setIsRead(false);
                newUserNotif.setCreatedAt(broadNotif.getCreatedAt());
                userNotifications.add(newUserNotif);
            }
        }
        userNotifications.sort((n1, n2) -> n2.getCreatedAt().compareTo(n1.getCreatedAt()));

        // Convert UserNotification entities to DTOs here
        return userNotifications.stream()
                .map(userNotif -> {
                    UserNotificationDTO dto = new UserNotificationDTO();
                    dto.setId(userNotif.getId());
                    dto.setUserId(userNotif.getUserId());
                    dto.setCreatedAt(userNotif.getCreatedAt());

                    if (userNotif.getNotification() != null) {
                        dto.setTitle(userNotif.getNotification().getTitle());
                        dto.setMessage(userNotif.getNotification().getMessage());
                        dto.setType(userNotif.getNotification().getType());
                    }
                    return dto;
                })
                .collect(Collectors.toList());
    }



    @Transactional
    public long getUnreadNotificationCount(String userId, String userRole) {
        return userNotificationRepository.countByUserIdAndIsReadFalse(userId);
    }


    @Transactional
    public void markAllNotificationsAsRead(String userId) {
        List<UserNotification> unreadPersonalizedNotifications = userNotificationRepository.findByUserIdAndIsReadFalseOrderByCreatedAtDesc(userId)
                .stream()
                .filter(un -> un.getNotification().getAudience() == null) // Filter for personalized
                .collect(Collectors.toList());

        for (UserNotification notification : unreadPersonalizedNotifications) {
            notification.setIsRead(true);
            userNotificationRepository.save(notification);
        }
    }

    // --- Admin-specific methods (CRUD for broad notifications) ---

    public Optional<Notification> getNotificationById(Long id) {
        return notificationRepository.findById(id);
    }

    @Transactional
    public Notification updateNotification(Long id, Notification updatedNotification, String authorizationHeader) {
        Optional<Notification> existingNotification = notificationRepository.findById(id);
        if (existingNotification.isPresent()) {
            Notification notification = existingNotification.get();
            notification.setTitle(updatedNotification.getTitle());
            notification.setMessage(updatedNotification.getMessage());
            notification.setType(updatedNotification.getType());
            notification.setAudience(updatedNotification.getAudience());
            notification.setCreatedBy(authService.getUserIdFromToken(authorizationHeader));
            return notificationRepository.save(notification);
        }
        return null;
    }

    @Transactional
    public void deleteNotification(Long id) {
        notificationRepository.deleteById(id);
    }

    public List<Notification> getAllBroadNotifications() {
        return notificationRepository.findAll().stream()
                .filter(n -> n.getAudience() != null)
                .collect(Collectors.toList());
    }

    public List<Notification> getAllNotifications() {
        return notificationRepository.findAll();
    }
}