package com.indraacademy.ias_management.service;

import com.indraacademy.ias_management.dto.UserNotificationDTO;
import com.indraacademy.ias_management.entity.Notification;
import com.indraacademy.ias_management.entity.Student;
import com.indraacademy.ias_management.entity.StudentStatus;
import com.indraacademy.ias_management.entity.Teacher;
import com.indraacademy.ias_management.entity.UserNotification;
import com.indraacademy.ias_management.repository.NotificationRepository;
import com.indraacademy.ias_management.repository.StudentRepository;
import com.indraacademy.ias_management.repository.TeacherRepository;
import com.indraacademy.ias_management.repository.UserNotificationRepository;
import com.indraacademy.ias_management.util.SecurityUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.dao.DataAccessException;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.JsonProcessingException;

import java.time.LocalDateTime;
import java.time.Period;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class NotificationService {

    private static final Logger log = LoggerFactory.getLogger(NotificationService.class);

    @Autowired private NotificationRepository notificationRepository;
    @Autowired private UserNotificationRepository userNotificationRepository;
    @Autowired private StudentRepository studentRepository;
    @Autowired private TeacherRepository teacherRepository;
    @Autowired private AuditService auditService;
    @Autowired private SecurityUtil securityUtil;
    @Autowired private ObjectMapper objectMapper;
    @Autowired private FcmService fcmService;

    @Transactional
    public Notification createBroadNotification(Notification notification,
                                                HttpServletRequest request) {

        if (notification == null || notification.getTitle() == null || notification.getMessage() == null) {
            throw new IllegalArgumentException("Notification object and its title/message must not be null.");
        }

        try {
            notification.setCreatedBy(securityUtil.getUsername());
            notification.setCreatedAt(LocalDateTime.now());

            Notification savedNotification = notificationRepository.save(notification);

            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "CREATE_NOTIFICATION",
                    "Notification",
                    savedNotification.getId().toString(),
                    null,
                    objectMapper.writeValueAsString(savedNotification),
                    request.getRemoteAddr()
            );

            // Send FCM push to all targeted users
            sendFcmForAudience(savedNotification.getAudience(),
                    savedNotification.getTitle(), savedNotification.getMessage());

            return savedNotification;

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not create broad notification", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public UserNotification createAutoGeneratedIndividualNotification(
            String title, String message, String type, String userId,
            String relatedEntityType, String relatedEntityId) {

        if (title == null || message == null || userId == null) {
            log.warn("Attempted to create individual notification with missing required fields for user: {}", userId);
            throw new IllegalArgumentException("Title, message, and user ID are required for individual notification.");
        }
        log.info("Creating individual notification for user: {} with title: {}", userId, title);

        try {
            // 1. Create and save the Notification entity
            Notification notification = new Notification();
            notification.setTitle(title);
            notification.setMessage(message);
            notification.setType(type);
            notification.setAudience(userId);
            notification.setCreatedAt(LocalDateTime.now());
            Notification savedNotification = notificationRepository.save(notification);

            // 2. Create and save the UserNotification entity
            UserNotification userNotification = new UserNotification();
            userNotification.setUserId(userId);
            userNotification.setNotification(savedNotification);
            userNotification.setIsRead(false);
            userNotification.setCreatedAt(LocalDateTime.now());

            UserNotification savedUserNotification = userNotificationRepository.save(userNotification);
            log.info("Individual notification created successfully for user: {}. Notification ID: {}", userId, savedNotification.getId());

            // Send FCM push to the individual user
            fcmService.sendToUser(userId, title, message);

            return savedUserNotification;
        } catch (DataAccessException e) {
            log.error("Data access error during individual notification creation for user: {}", userId, e);
            throw new RuntimeException("Could not create individual notification due to data access issue", e);
        }
    }


    @Transactional
    public List<UserNotificationDTO> getNotificationsForUser(String userId, String userRole) {
        if (userId == null || userRole == null) {
            log.warn("Attempted to fetch notifications with null user ID or role.");
            return Collections.emptyList();
        }
        log.info("Fetching notifications for user: {} with role: {}", userId, userRole);

        // Resolve extra context needed for audience matching
        String studentClassName = null;
        String teacherAssignedClass = null;

        if ("STUDENT".equalsIgnoreCase(userRole)) {
            try {
                studentClassName = studentRepository.findByStudentId(userId)
                        .map(Student::getClassName)
                        .orElse(null);
            } catch (DataAccessException e) {
                log.warn("Could not resolve class name for student: {}", userId, e);
            }
        } else if ("TEACHER".equalsIgnoreCase(userRole)) {
            try {
                teacherAssignedClass = teacherRepository.findById(userId)
                        .map(Teacher::getClassTeacher)
                        .orElse(null);
            } catch (DataAccessException e) {
                log.warn("Could not resolve assigned class for teacher: {}", userId, e);
            }
        }
        final String resolvedClassName = studentClassName;
        final String resolvedTeacherClass = teacherAssignedClass;

        List<UserNotification> userNotifications;
        List<Notification> broadNotifications;

        try {
            // 1. Fetch existing user-specific notifications
            userNotifications = new ArrayList<>(userNotificationRepository.findByUserIdOrderByCreatedAtDesc(userId));

            // 2. Fetch broad/general notifications applicable to this user
            broadNotifications = notificationRepository.findAll().stream()
                    .filter(notification -> {
                        String audience = notification.getAudience();
                        if (audience == null) return false;

                        if ("STUDENT".equalsIgnoreCase(userRole)) {
                            return "ALL".equalsIgnoreCase(audience)
                                    || "STUDENTS".equalsIgnoreCase(audience)
                                    || userId.equals(audience)
                                    || (resolvedClassName != null && audience.equalsIgnoreCase("CLASS:" + resolvedClassName))
                                    || (resolvedClassName != null && audience.equalsIgnoreCase("CLASS_WITH_TEACHER:" + resolvedClassName));
                        } else if ("TEACHER".equalsIgnoreCase(userRole)) {
                            return "ALL".equalsIgnoreCase(audience)
                                    || "TEACHERS".equalsIgnoreCase(audience)
                                    || userId.equals(audience)
                                    || (resolvedTeacherClass != null && audience.equalsIgnoreCase("CLASS_WITH_TEACHER:" + resolvedTeacherClass));
                        }
                        return false;
                    })
                    .toList();
        } catch (DataAccessException e) {
            log.error("Data access error during notification fetch for user: {}", userId, e);
            throw new RuntimeException("Could not retrieve notifications due to data access issue", e);
        }

        // 3. Create UserNotification entries for applicable broad notifications if they don't exist yet
        int newNotificationsCount = 0;
        for (Notification broadNotif : broadNotifications) {
            try {
                if (!userNotificationRepository.existsByUserIdAndNotificationId(userId, broadNotif.getId())) {
                    UserNotification newUserNotif = new UserNotification();
                    newUserNotif.setUserId(userId);
                    newUserNotif.setNotification(broadNotif);
                    newUserNotif.setIsRead(false);
                    newUserNotif.setCreatedAt(broadNotif.getCreatedAt());
                    userNotifications.add(userNotificationRepository.save(newUserNotif));
                    newNotificationsCount++;
                }
            } catch (DataAccessException e) {
                log.error("Data access error creating UserNotification for broad notification ID: {} for user: {}", broadNotif.getId(), userId, e);
            }
        }
        log.debug("Created {} new UserNotification entries for user {}.", newNotificationsCount, userId);

        // 4. Sort combined list newest-first
        userNotifications.sort((n1, n2) -> n2.getCreatedAt().compareTo(n1.getCreatedAt()));

        // 5. Convert to DTOs
        return userNotifications.stream()
                .map(userNotif -> {
                    UserNotificationDTO dto = new UserNotificationDTO();
                    dto.setId(userNotif.getId());
                    dto.setUserId(userNotif.getUserId());
                    dto.setIsRead(userNotif.getIsRead());
                    dto.setCreatedAt(userNotif.getCreatedAt());

                    Notification notification = userNotif.getNotification();
                    if (notification != null) {
                        dto.setTitle(notification.getTitle());
                        dto.setMessage(notification.getMessage());
                        dto.setType(notification.getType());
                    }
                    return dto;
                })
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public long getUnreadNotificationCount(String userId, String userRole) {
        if (userId == null) {
            log.warn("Attempted to get unread count with null user ID.");
            return 0;
        }
        log.info("Counting unread notifications for user: {}", userId);
        try {
            return userNotificationRepository.countByUserIdAndIsReadFalse(userId);
        } catch (DataAccessException e) {
            log.error("Data access error counting unread notifications for user: {}", userId, e);
            throw new RuntimeException("Could not retrieve unread notification count due to data access issue", e);
        }
    }


    @Transactional
    public void markAllNotificationsAsRead(String userId) {
        if (userId == null) {
            log.warn("Attempted to mark notifications as read with null user ID.");
            return;
        }
        log.info("Marking all unread notifications as read for user: {}", userId);

        try {
            List<UserNotification> unread = userNotificationRepository.findByUserIdAndIsReadFalseOrderByCreatedAtDesc(userId);
            for (UserNotification un : unread) {
                un.setIsRead(true);
                userNotificationRepository.save(un);
            }
            log.info("Marked {} notifications as read for user: {}", unread.size(), userId);
        } catch (DataAccessException e) {
            log.error("Data access error marking notifications as read for user: {}", userId, e);
            throw new RuntimeException("Could not mark notifications as read due to data access issue", e);
        }
    }

    // --- Admin-specific methods (CRUD for broad notifications) ---

    @Transactional(readOnly = true)
    public Optional<Notification> getNotificationById(Long id) {
        if (id == null) {
            log.warn("Attempted to get notification with null ID.");
            return Optional.empty();
        }
        log.info("Fetching notification by ID: {}", id);
        try {
            return notificationRepository.findById(id);
        } catch (DataAccessException e) {
            log.error("Data access error fetching notification ID: {}", id, e);
            throw new RuntimeException("Could not retrieve notification due to data access issue", e);
        }
    }

    @Transactional
    public Notification updateNotification(Long id,
                                           Notification updatedNotification,
                                           HttpServletRequest request) {

        if (id == null || updatedNotification == null) {
            throw new IllegalArgumentException("Notification ID and details must not be null.");
        }

        try {
            Notification notification = notificationRepository.findById(id)
                    .orElseThrow(() -> new IllegalArgumentException("Notification not found with ID: " + id));

            String oldValue = objectMapper.writeValueAsString(notification);

            notification.setTitle(updatedNotification.getTitle());
            notification.setMessage(updatedNotification.getMessage());
            notification.setType(updatedNotification.getType());
            notification.setAudience(updatedNotification.getAudience());

            notification.setCreatedBy(securityUtil.getUsername()); // acting as updatedBy

            Notification savedNotification = notificationRepository.save(notification);

            auditService.logUpdate(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "UPDATE_NOTIFICATION",
                    "Notification",
                    id.toString(),
                    oldValue,
                    objectMapper.writeValueAsString(savedNotification),
                    request.getRemoteAddr()
            );

            return savedNotification;

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not update notification", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional
    public void deleteNotification(Long id, HttpServletRequest request) {

        if (id == null) {
            throw new IllegalArgumentException("Notification ID must not be null.");
        }

        try {
            Notification notification = notificationRepository.findById(id)
                    .orElseThrow(() -> new IllegalArgumentException("Notification not found with ID: " + id));

            String oldValue = objectMapper.writeValueAsString(notification);

            notificationRepository.deleteById(id);

            auditService.log(
                    securityUtil.getUsername(),
                    securityUtil.getRole(),
                    "DELETE_NOTIFICATION",
                    "Notification",
                    id.toString(),
                    oldValue,
                    null,
                    request.getRemoteAddr()
            );

        } catch (DataAccessException e) {
            throw new RuntimeException("Could not delete notification", e);
        } catch (JsonProcessingException e) {
            throw new RuntimeException(e);
        }
    }

    @Transactional(readOnly = true)
    public List<Notification> getAllBroadNotifications() {
        log.info("Fetching all broad notifications.");
        try {
            return notificationRepository.findAll().stream()
                    .filter(n -> n.getAudience() != null)
                    .collect(Collectors.toList());
        } catch (DataAccessException e) {
            log.error("Data access error fetching all broad notifications.", e);
            throw new RuntimeException("Could not retrieve broad notifications due to data access issue", e);
        }
    }

    @Transactional(readOnly = true)
    public List<Notification> getAllNotifications() {
        log.info("Fetching all notifications with a creator.");
        try {
            return notificationRepository.findByCreatedByIsNotNull();
        } catch (DataAccessException e) {
            log.error("Data access error fetching all notifications.", e);
            throw new RuntimeException("Could not retrieve all notifications due to data access issue", e);
        }
    }

    // ─── FCM audience resolution ──────────────────────────────────────────────

    /**
     * Resolves the audience string to a list of userIds and dispatches FCM pushes.
     * Audience values mirror the frontend convention:
     *   "ALL"                   → every active student + every teacher
     *   "STUDENTS"              → every active student
     *   "TEACHERS"              → every teacher
     *   "CLASS:X"               → active students in class X
     *   "CLASS_WITH_TEACHER:X"  → active students in class X + class teacher of X
     *   <any other value>       → treated as a single userId
     */
    private void sendFcmForAudience(String audience, String title, String body) {
        if (audience == null || audience.isBlank()) return;

        try {
            if ("ALL".equalsIgnoreCase(audience)) {
                List<String> studentIds = studentRepository.findByStatus(StudentStatus.ACTIVE)
                        .stream().map(Student::getStudentId).collect(Collectors.toList());
                List<String> teacherIds = teacherRepository.findAll()
                        .stream().map(Teacher::getTeacherId).collect(Collectors.toList());
                fcmService.sendToUsers(studentIds, title, body);
                fcmService.sendToUsers(teacherIds, title, body);

            } else if ("STUDENTS".equalsIgnoreCase(audience)) {
                List<String> ids = studentRepository.findByStatus(StudentStatus.ACTIVE)
                        .stream().map(Student::getStudentId).collect(Collectors.toList());
                fcmService.sendToUsers(ids, title, body);

            } else if ("TEACHERS".equalsIgnoreCase(audience)) {
                List<String> ids = teacherRepository.findAll()
                        .stream().map(Teacher::getTeacherId).collect(Collectors.toList());
                fcmService.sendToUsers(ids, title, body);

            } else if (audience.toUpperCase().startsWith("CLASS:")) {
                String className = audience.substring("CLASS:".length());
                List<String> ids = studentRepository
                        .findByClassNameAndStatus(className, StudentStatus.ACTIVE)
                        .stream().map(Student::getStudentId).collect(Collectors.toList());
                fcmService.sendToUsers(ids, title, body);

            } else if (audience.toUpperCase().startsWith("CLASS_WITH_TEACHER:")) {
                String className = audience.substring("CLASS_WITH_TEACHER:".length());
                List<String> studentIds = studentRepository
                        .findByClassNameAndStatus(className, StudentStatus.ACTIVE)
                        .stream().map(Student::getStudentId).collect(Collectors.toList());
                fcmService.sendToUsers(studentIds, title, body);
                teacherRepository.findByClassTeacher(className)
                        .ifPresent(t -> fcmService.sendToUser(t.getTeacherId(), title, body));

            } else {
                // Treat as a specific userId
                fcmService.sendToUser(audience, title, body);
            }
        } catch (Exception e) {
            log.warn("FCM audience dispatch failed for audience '{}': {}", audience, e.getMessage());
        }
    }

    @Scheduled(cron = "0 0 2 * * ?")
    @Transactional
    public void cleanupOldNotifications() {
        log.info("Starting scheduled cleanup of old notifications.");
        try {
            LocalDateTime oneMonthAgo = LocalDateTime.now().minus(Period.ofMonths(1));
            List<Notification> oldNotifications = notificationRepository.findByCreatedAtBefore(oneMonthAgo);

            for (Notification notification : oldNotifications) {
                // Ensure proper cascade/manual deletion of UserNotification first if necessary,
                // though JPA cascade annotations should handle it.
                notificationRepository.delete(notification);
            }
            log.info("Cleaned up {} old notifications created before {}", oldNotifications.size(), oneMonthAgo);
        } catch (DataAccessException e) {
            log.error("Data access error during scheduled notification cleanup.", e);
        }
    }
}