spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Extra production safety
server.error.include-stacktrace=never
server.error.include-message=never

# HTTP security
auth.cookie.secure=true
auth.cookie.sameSite=Strict