spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Extra production safety
server.error.include-stacktrace=never
server.error.include-message=never