package com.indraacademy.ias_management.notification;

public enum NotificationEventCode {
    NOTICE_PUBLISHED,
    LEAVE_SUBMITTED,
    LEAVE_APPROVED,
    LEAVE_REJECTED,
    LEAVE_CANCELLED,
    PAYMENT_SUCCESS,
    PAYMENT_REFUNDED,
    FEE_DUE,
    FEE_OVERDUE,
    STUDENT_ABSENT,
    ATTENDANCE_LOW,
    REPORT_CARD_READY,
    EVENT_PUBLISHED,
    HOLIDAY_PUBLISHED,
    FEE_REMINDER,
    ATTENDANCE_REMINDER,
    ACCOUNT_SECURITY,
    LEGACY_NOTIFICATION
}
