-- V13__ai_teacher_attendance_reminder_batch.sql
-- Durable, Spring-owned record of one AI-copilot-triggered TEACHER-initiated attendance
-- reminder batch — structural mirror of ai_attendance_reminder_batch (see
-- V12__ai_attendance_reminder_batch.sql), with class_name NOT NULL (a teacher batch always
-- belongs to exactly one class) and a teacher_user_id column instead of admin_user_id.

CREATE TABLE public.ai_teacher_attendance_reminder_batch (
    id bigint NOT NULL,
    teacher_user_id character varying(64) NOT NULL,
    class_name character varying(64) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    failed_count integer NOT NULL,
    outcomes text,
    school_id bigint NOT NULL,
    sent_count integer NOT NULL,
    session character varying(16) NOT NULL,
    status character varying(32) NOT NULL,
    student_ids text NOT NULL,
    threshold double precision NOT NULL DEFAULT 75.0,
    workflow_id character varying(64) NOT NULL
);

ALTER TABLE public.ai_teacher_attendance_reminder_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_teacher_attendance_reminder_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_teacher_attendance_reminder_batch
    ADD CONSTRAINT ai_teacher_attendance_reminder_batch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_teacher_attendance_reminder_batch
    ADD CONSTRAINT uk_ai_teacher_attendance_reminder_batch_workflow_id UNIQUE (workflow_id);

CREATE INDEX idx_ai_teacher_attendance_reminder_batch_school ON public.ai_teacher_attendance_reminder_batch USING btree (school_id);
CREATE INDEX idx_ai_teacher_attendance_reminder_batch_teacher ON public.ai_teacher_attendance_reminder_batch USING btree (teacher_user_id);
