-- V15__ai_leave_decision_batch.sql
-- Durable, Spring-owned record of one AI-copilot-proposed leave approve/reject batch —
-- structural sibling of ai_teacher_attendance_reminder_batch (V13), sharing the same lifecycle
-- status vocabulary so all four AI workflows have one state machine rather than four.
--
-- Two columns differ from the reminder batches, for reasons specific to leave decisions:
--   * decision      — APPROVE or REJECT the leave, recorded separately from the batch's own
--                     approval status. A batch can be REJECTED (the admin declined to act) while
--                     its decision was APPROVED (what would have happened), and collapsing the
--                     two would make the audit trail unreadable.
--   * skipped_count — leaves deliberately left untouched at apply time because they were no
--                     longer PENDING (someone else already decided), were deleted, or fell
--                     outside a teacher batch's class. Distinct from failed_count: a skip is a
--                     correct refusal to overwrite someone else's decision, not an error.

CREATE TABLE public.ai_leave_decision_batch (
    id bigint NOT NULL,
    workflow_id character varying(64) NOT NULL,
    school_id bigint NOT NULL,
    requester_user_id character varying(64) NOT NULL,
    requester_role character varying(32) NOT NULL,
    class_name character varying(64),
    decision character varying(16) NOT NULL,
    leave_ids text NOT NULL,
    status character varying(32) NOT NULL,
    applied_count integer NOT NULL,
    skipped_count integer NOT NULL,
    failed_count integer NOT NULL,
    outcomes text,
    created_at timestamp(6) without time zone NOT NULL,
    completed_at timestamp(6) without time zone
);

ALTER TABLE public.ai_leave_decision_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_leave_decision_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_leave_decision_batch
    ADD CONSTRAINT ai_leave_decision_batch_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ai_leave_decision_batch
    ADD CONSTRAINT uk_ai_leave_decision_batch_workflow_id UNIQUE (workflow_id);

CREATE INDEX idx_ai_leave_decision_batch_school ON public.ai_leave_decision_batch USING btree (school_id);
CREATE INDEX idx_ai_leave_decision_batch_requester ON public.ai_leave_decision_batch USING btree (requester_user_id);
