-- V17__teacher_leave.sql
-- Teacher-initiated leave applications — the piece missing when TeacherAttendance.status
-- ON_LEAVE was previously only ever set by manual admin override, with nothing for a teacher
-- to actually apply through. A date range (start_date/end_date), not one row per day — see
-- TeacherLeave's Javadoc.

CREATE TABLE public.teacher_leave (
    id bigint NOT NULL,
    school_id bigint NOT NULL,
    teacher_id character varying(64) NOT NULL,
    teacher_name character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    reason text NOT NULL,
    status character varying(20) NOT NULL DEFAULT 'PENDING',
    applied_date timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.teacher_leave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_leave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.teacher_leave
    ADD CONSTRAINT teacher_leave_pkey PRIMARY KEY (id);

CREATE INDEX idx_teacher_leave_teacher ON public.teacher_leave USING btree (teacher_id, school_id);
CREATE INDEX idx_teacher_leave_school_status ON public.teacher_leave USING btree (school_id, status);
CREATE INDEX idx_teacher_leave_dates ON public.teacher_leave USING btree (school_id, start_date, end_date);
