-- ============================================================================
-- V1: Canonical schema baseline.
-- ============================================================================
-- Flyway becomes the sole authority for schema going forward (see the Phase 5C
-- re-baseline report). This migration is NOT a literal replay of the old V1-V26 history —
-- those files were largely never executed by Flyway at all (this application ran on
-- Hibernate ddl-auto=update from the start; Flyway was added later, several migrations
-- were written in MySQL syntax the app never actually used on Postgres, and everything
-- from the "invoice sequence counter" baseline point onward was silently skipped). Rather
-- than repair 26 migrations' worth of broken/never-run history for its own
-- sake, this migration captures what Hibernate actually built in the current environment
-- (via pg_dump --schema-only against the live dev database) as ground truth, MINUS the
-- objects a fresh install should not carry forward:
--
--   - flyway_schema_history: Flyway manages this table itself; never hand-create it.
--   - 6 orphaned transport-tracking tables (bus, driver, driver_default_assignment,
--     transport_route, transport_stop, student_bus_assignment) plus 3 more from the same
--     removed live-tracking feature (boarding_event, student_absence_flag, trip) — zero
--     JPA entities and zero code references anywhere in the backend map to any of these
--     nine; confirmed via full-codebase grep before exclusion. The feature was removed;
--     these tables were just never dropped.
--   - daily_schedule_override: zero code references anywhere; abandoned, cause unknown.
--   - invoice_number_seq: superseded by InvoiceGenerationService.generateInvoiceNumber's
--     query-based MAX(invoice_number)+1 approach; the table-based counter it was built for
--     is dead code today.
--   - Six financial tables/column groups that the numbered migrations following this one
--     (V2-V11, carrying forward the intent of the old V27-V36 "financial hardening phase")
--     are responsible for creating WITH their full constraint sets: StudentFees'
--     base_amount_due/bus_fee_due/discount_amount/amount_computed_at/amount_rule_snapshot/
--     snapshot_status columns, Payment's manual_payment_mode/manual_reference_number
--     columns, and the payment_order/refund/payment_student_fees_allocation/
--     allocation_refund/student_one_time_fee_charged/student_fees_line_item tables. These
--     already exist as bare Hibernate-created tables in the current dev DB with NONE of
--     their intended CHECK constraints or partial unique indexes (Hibernate ddl-auto never
--     created those) — leaving them in this baseline would make V2-V11's own
--     "CREATE TABLE IF NOT EXISTS" / "ADD COLUMN IF NOT EXISTS" statements silently no-op
--     and skip adding the missing constraints entirely. Excluding them here and letting
--     V2-V11 create them from a clean slate is what makes those constraints actually apply.
--
-- Every other object below (69 tables, sequences, indexes, FKs, CHECK constraints) is
-- reproduced exactly as Hibernate + the handful of migrations that DID historically run
-- (the "invoice sequence counter"/"invoice optimistic lock version" baseline) built it —
-- this is real, currently-running schema, not a reconstruction from memory.
-- ============================================================================

-- Name: vector; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: academic_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_session (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_current boolean NOT NULL,
    end_date date NOT NULL,
    label character varying(20) NOT NULL,
    school_id bigint NOT NULL,
    start_date date NOT NULL
);


--
-- Name: academic_session_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_session ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_session_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academic_stream; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.academic_stream (
    id bigint NOT NULL,
    school_id bigint,
    stream_name character varying(255) NOT NULL
);


--
-- Name: academic_stream_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.academic_stream ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.academic_stream_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin (
    admin_id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    dob date NOT NULL,
    email character varying(255) NOT NULL,
    gender character varying(255),
    name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    photo_url character varying(255),
    school_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: ai_fee_reminder_batch; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_fee_reminder_batch (
    id bigint NOT NULL,
    admin_user_id character varying(64) NOT NULL,
    class_name character varying(64),
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    failed_count integer NOT NULL,
    outcomes text,
    school_id bigint NOT NULL,
    sent_count integer NOT NULL,
    session character varying(16) NOT NULL,
    status character varying(32) NOT NULL,
    student_ids text NOT NULL,
    workflow_id character varying(64) NOT NULL
);


--
-- Name: ai_fee_reminder_batch_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_fee_reminder_batch ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_fee_reminder_batch_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_trace_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_trace_event (
    id bigint NOT NULL,
    completion_tokens integer,
    conversation_id character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    error_message text,
    errored boolean NOT NULL,
    final_reply text,
    interrupted boolean NOT NULL,
    prompt_tokens integer,
    rag_results_json text,
    role character varying(20) NOT NULL,
    school_id bigint NOT NULL,
    tools_called_json text,
    total_latency_ms bigint,
    total_tokens integer,
    trace_id character varying(64) NOT NULL,
    user_id character varying(255) NOT NULL,
    user_message text,
    workflow_id character varying(255)
);


--
-- Name: ai_trace_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_trace_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_trace_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_group (
    id bigint NOT NULL,
    class_name character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    display_name character varying(255),
    display_order integer NOT NULL,
    group_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    school_id bigint NOT NULL,
    session character varying(255) NOT NULL
);


--
-- Name: assessment_group_composition; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_group_composition (
    id bigint NOT NULL,
    child_group_id bigint NOT NULL,
    display_order integer NOT NULL,
    parent_group_id bigint NOT NULL,
    school_id bigint NOT NULL,
    weightage numeric(5,4) NOT NULL
);


--
-- Name: assessment_group_composition_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_group_composition ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_group_composition_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_group_exam_mapping; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_group_exam_mapping (
    id bigint NOT NULL,
    assessment_group_id bigint NOT NULL,
    display_order integer NOT NULL,
    exam_config_id bigint NOT NULL,
    school_id bigint NOT NULL,
    weightage numeric(5,4) NOT NULL
);


--
-- Name: assessment_group_exam_mapping_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_group_exam_mapping ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_group_exam_mapping_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: assessment_group_result; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.assessment_group_result (
    id bigint NOT NULL,
    assessment_group_id bigint NOT NULL,
    computed_at timestamp(6) without time zone,
    rank_position integer,
    school_id bigint NOT NULL,
    session character varying(10) NOT NULL,
    student_id character varying(50) NOT NULL,
    total_max numeric(8,2),
    total_obtained numeric(8,2),
    weighted_score numeric(8,4)
);


--
-- Name: assessment_group_result_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.assessment_group_result ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.assessment_group_result_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    charge_paid boolean NOT NULL,
    class_name character varying(255),
    date date,
    school_id bigint,
    student_id character varying(255),
    class_id bigint,
    marked_by character varying(100),
    section_id bigint,
    status character varying(20)
);


--
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log (
    id bigint NOT NULL,
    action character varying(255),
    entity_id character varying(255),
    entity_name character varying(255),
    ip_address character varying(255),
    new_value text,
    old_value text,
    role character varying(255),
    school_id bigint,
    "timestamp" timestamp(6) without time zone,
    username character varying(255)
);


--
-- Name: audit_log_archive; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_log_archive (
    id bigint NOT NULL,
    action character varying(255),
    entity_id character varying(255),
    entity_name character varying(255),
    ip_address character varying(255),
    new_value text,
    old_value text,
    role character varying(255),
    school_id bigint,
    "timestamp" timestamp(6) without time zone,
    username character varying(255)
);


--
-- Name: audit_log_archive_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log_archive ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_archive_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bus_fees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bus_fees (
    id bigint NOT NULL,
    academic_year character varying(255) NOT NULL,
    fees numeric(38,2) NOT NULL,
    max_distance double precision,
    min_distance double precision NOT NULL,
    school_id bigint
);


--
-- Name: bus_fees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bus_fees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bus_fees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: class_subject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class_subject (
    id bigint NOT NULL,
    class_name character varying(255) NOT NULL,
    school_id bigint,
    subject_name character varying(255) NOT NULL,
    class_id bigint,
    optional_group character varying(255),
    is_elective boolean DEFAULT false NOT NULL
);


--
-- Name: class_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: co_scholastic_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.co_scholastic_entry (
    id bigint NOT NULL,
    activity character varying(100) NOT NULL,
    entered_at timestamp(6) without time zone NOT NULL,
    entered_by character varying(100),
    grade character varying(10),
    school_id bigint NOT NULL,
    session character varying(20) NOT NULL,
    student_id character varying(30) NOT NULL,
    template_id bigint NOT NULL
);


--
-- Name: co_scholastic_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.co_scholastic_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.co_scholastic_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: credit_note; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.credit_note (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    approved_at timestamp(6) without time zone,
    approved_by character varying(100),
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100) NOT NULL,
    credit_type character varying(20) NOT NULL,
    reason character varying(500) NOT NULL,
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    student_id character varying(50) NOT NULL,
    invoice_id bigint,
    CONSTRAINT credit_note_credit_type_check CHECK (((credit_type)::text = ANY ((ARRAY['REFUND'::character varying, 'ADJUSTMENT'::character varying, 'WRITE_OFF'::character varying, 'FEE_WAIVER'::character varying])::text[]))),
    CONSTRAINT credit_note_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'APPLIED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: credit_note_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.credit_note ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.credit_note_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: demo_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.demo_requests (
    id bigint NOT NULL,
    city character varying(150),
    contact_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    message text,
    number_of_students character varying(50),
    phone character varying(50) NOT NULL,
    requested_at timestamp(6) without time zone NOT NULL,
    school_name character varying(255) NOT NULL,
    status character varying(20) NOT NULL,
    CONSTRAINT demo_requests_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('CONTACTED'::character varying)::text, ('COMPLETED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


--
-- Name: demo_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.demo_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.demo_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    school_id bigint,
    token character varying(4096) NOT NULL,
    user_id character varying(255) NOT NULL
);


--
-- Name: device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_target_audience; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_target_audience (
    event_id bigint NOT NULL,
    audience_type character varying(255) NOT NULL
);


--
-- Name: event_video_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_video_links (
    event_id bigint NOT NULL,
    video_url character varying(255)
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    created_at date NOT NULL,
    created_by character varying(255) NOT NULL,
    description text NOT NULL,
    end_date date,
    end_time time(6) without time zone,
    image_url character varying(255),
    location character varying(255),
    school_id bigint,
    start_date date NOT NULL,
    start_time time(6) without time zone,
    title character varying(255) NOT NULL,
    updated_at date
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_config (
    id bigint NOT NULL,
    class_name character varying(255) NOT NULL,
    exam_name character varying(255) NOT NULL,
    school_id bigint,
    session character varying(255) NOT NULL,
    class_id bigint
);


--
-- Name: exam_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exam_subject_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exam_subject_entry (
    id bigint NOT NULL,
    exam_config_id bigint NOT NULL,
    exam_date date,
    max_marks integer NOT NULL,
    school_id bigint,
    subject_name character varying(255) NOT NULL
);


--
-- Name: exam_subject_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exam_subject_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exam_subject_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: feature_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feature_catalog (
    feature_key character varying(60) NOT NULL,
    category character varying(50),
    description text,
    display_name character varying(255) NOT NULL,
    is_always_on boolean NOT NULL
);


--
-- Name: feature_catalog_dependencies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.feature_catalog_dependencies (
    feature_key character varying(60) NOT NULL,
    depends_on_feature_key character varying(60)
);


--
-- Name: fee_head; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_head (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    display_order integer NOT NULL,
    due_months text NOT NULL,
    frequency character varying(20) NOT NULL,
    name character varying(100) NOT NULL,
    is_optional boolean NOT NULL,
    is_refundable boolean NOT NULL,
    school_id bigint NOT NULL,
    sibling_discount_pct numeric(5,2),
    updated_at timestamp(6) without time zone,
    CONSTRAINT fee_head_frequency_check CHECK (((frequency)::text = ANY ((ARRAY['MONTHLY'::character varying, 'QUARTERLY'::character varying, 'SEMI_ANNUAL'::character varying, 'ANNUAL'::character varying, 'ONE_TIME'::character varying])::text[])))
);


--
-- Name: fee_head_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_head ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_head_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_payment (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    notes character varying(500),
    payment_date timestamp(6) without time zone NOT NULL,
    payment_mode character varying(20) NOT NULL,
    razorpay_order_id character varying(50),
    razorpay_payment_id character varying(50),
    razorpay_signature character varying(255),
    received_by character varying(100),
    reference_number character varying(100),
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    student_id character varying(50) NOT NULL,
    CONSTRAINT fee_payment_payment_mode_check CHECK (((payment_mode)::text = ANY ((ARRAY['RAZORPAY'::character varying, 'MANUAL_CASH'::character varying, 'MANUAL_CHEQUE'::character varying, 'BANK_TRANSFER'::character varying, 'UPI'::character varying])::text[]))),
    CONSTRAINT fee_payment_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying, 'REFUNDED'::character varying])::text[])))
);


--
-- Name: fee_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_structure; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structure (
    id bigint NOT NULL,
    academic_year character varying(255),
    admission_fee double precision,
    annual_charges double precision,
    class_name character varying(255),
    eca_project double precision,
    examination_fee double precision,
    lab_charges double precision,
    school_id bigint,
    tuition_fee double precision,
    class_id bigint
);


--
-- Name: fee_structure_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structure ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structure_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fee_structure_rule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fee_structure_rule (
    id bigint NOT NULL,
    amount bigint NOT NULL,
    class_name character varying(50) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    effective_from date NOT NULL,
    effective_until date,
    school_id bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    academic_session_id bigint NOT NULL,
    fee_head_id bigint NOT NULL,
    class_id bigint
);


--
-- Name: fee_structure_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fee_structure_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fee_structure_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: global_subscription_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.global_subscription_config (
    config_id integer NOT NULL,
    default_trial_days integer NOT NULL,
    expiry_notify_days integer NOT NULL,
    grace_period_days integer NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by_admin_id character varying(100)
);


--
-- Name: invoice; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice (
    id bigint NOT NULL,
    amount_paid bigint NOT NULL,
    balance_due bigint NOT NULL,
    billing_month integer NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    discount_amount bigint NOT NULL,
    due_date date NOT NULL,
    invoice_number character varying(30) NOT NULL,
    issued_at timestamp(6) without time zone,
    net_amount bigint NOT NULL,
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    student_id character varying(50) NOT NULL,
    total_amount bigint NOT NULL,
    updated_at timestamp(6) without time zone,
    academic_session_id bigint NOT NULL,
    version bigint NOT NULL,
    CONSTRAINT invoice_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'ISSUED'::character varying, 'PARTIALLY_PAID'::character varying, 'PAID'::character varying, 'OVERDUE'::character varying, 'CANCELLED'::character varying, 'WRITTEN_OFF'::character varying])::text[])))
);


--
-- Name: invoice_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoice ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: invoice_line_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.invoice_line_item (
    id bigint NOT NULL,
    base_amount bigint NOT NULL,
    description character varying(200),
    discount_amount bigint NOT NULL,
    fee_head_code character varying(30) NOT NULL,
    net_amount bigint NOT NULL,
    fee_head_id bigint NOT NULL,
    invoice_id bigint NOT NULL
);


--
-- Name: invoice_line_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.invoice_line_item ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoice_line_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_chunk; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_chunk (
    id bigint NOT NULL,
    chunk_index integer NOT NULL,
    chunk_text text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    document_id bigint NOT NULL,
    school_id bigint NOT NULL,
    embedding public.vector(1536),
    page_number integer
);


--
-- Name: knowledge_chunk_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_chunk ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_chunk_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: knowledge_document; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.knowledge_document (
    id bigint NOT NULL,
    category character varying(30) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    error_message text,
    original_filename character varying(255) NOT NULL,
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    storage_path character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    uploaded_by_admin_id character varying(255)
);


--
-- Name: knowledge_document_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.knowledge_document ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.knowledge_document_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: leaves; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.leaves (
    id bigint NOT NULL,
    applied_date timestamp(6) without time zone NOT NULL,
    class_name character varying(255) NOT NULL,
    leave_date character varying(255) NOT NULL,
    reason text NOT NULL,
    school_id bigint,
    status character varying(20) NOT NULL,
    student_id character varying(255) NOT NULL,
    student_name character varying(255) NOT NULL,
    class_id bigint,
    CONSTRAINT leaves_status_check CHECK (((status)::text = ANY (ARRAY[('PENDING'::character varying)::text, ('APPROVED'::character varying)::text, ('REJECTED'::character varying)::text])))
);


--
-- Name: leaves_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.leaves ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leaves_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_channels (
    id bigint NOT NULL,
    channel_type character varying(20) NOT NULL,
    config_json text,
    enabled boolean NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: notification_channels_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_channels ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_channels_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    audience character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(255),
    message text NOT NULL,
    school_id bigint,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    channel character varying(20)
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: optional_subject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.optional_subject (
    id bigint NOT NULL,
    group_id bigint NOT NULL,
    school_id bigint,
    subject_name character varying(255) NOT NULL
);


--
-- Name: optional_subject_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.optional_subject_group (
    id bigint NOT NULL,
    group_name character varying(255) NOT NULL,
    school_id bigint
);


--
-- Name: optional_subject_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.optional_subject_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.optional_subject_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: optional_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.optional_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.optional_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment (
    id bigint NOT NULL,
    additional_charges integer,
    amount integer NOT NULL,
    amount_paid integer,
    annual_charges integer,
    bus_fee integer,
    class_name character varying(255) NOT NULL,
    eca_project integer,
    examination_fee integer,
    lab_charges integer,
    late_fees integer,
    month character varying(255) NOT NULL,
    order_id character varying(255) NOT NULL,
    paid_manually boolean,
    payment_date timestamp(6) without time zone NOT NULL,
    payment_id character varying(255) NOT NULL,
    platform_fee integer,
    razorpay_signature character varying(255) NOT NULL,
    school_id bigint,
    session character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    student_id character varying(255) NOT NULL,
    student_name character varying(255) NOT NULL,
    tuition_fee integer,
    class_id bigint
);


--
-- Name: payment_allocation; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payment_allocation (
    id bigint NOT NULL,
    amount_allocated bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    fee_payment_id bigint NOT NULL,
    invoice_id bigint NOT NULL
);


--
-- Name: payment_allocation_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment_allocation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_allocation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permission (
    permission_key character varying(60) NOT NULL,
    category character varying(50),
    description character varying(255),
    display_name character varying(100) NOT NULL
);


--
-- Name: plan_feature_changes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_feature_changes (
    id bigint NOT NULL,
    action_type character varying(10) NOT NULL,
    applied boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    effective_at timestamp(6) without time zone,
    feature_key character varying(60) NOT NULL,
    plan_id bigint NOT NULL,
    policy character varying(30)
);


--
-- Name: plan_feature_changes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plan_feature_changes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plan_feature_changes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plan_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plan_features (
    feature_key character varying(60) NOT NULL,
    plan_id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL
);


--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    id bigint NOT NULL,
    annual_price_paise bigint,
    created_at timestamp(6) without time zone NOT NULL,
    currency character varying(10) NOT NULL,
    is_active boolean NOT NULL,
    is_public boolean NOT NULL,
    max_staff integer,
    max_students integer,
    monthly_price_paise bigint,
    name character varying(255) NOT NULL,
    priority_score integer NOT NULL,
    staff_hard_limit_pct integer,
    staff_soft_limit_pct integer,
    storage_gb_limit integer,
    storage_hard_limit_pct integer,
    storage_soft_limit_pct integer,
    student_hard_limit_pct integer,
    student_soft_limit_pct integer,
    tier character varying(50) NOT NULL,
    updated_at timestamp(6) without time zone,
    version character varying(20)
);


--
-- Name: plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_card_publication; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_card_publication (
    id bigint NOT NULL,
    class_name character varying(50) NOT NULL,
    email_count integer NOT NULL,
    email_sent_at timestamp(6) without time zone,
    published_at timestamp(6) without time zone NOT NULL,
    published_by character varying(150),
    school_id bigint NOT NULL,
    session character varying(20) NOT NULL,
    template_id bigint NOT NULL,
    verification_token character varying(36)
);


--
-- Name: report_card_publication_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_card_publication ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_card_publication_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_card_remark; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_card_remark (
    id bigint NOT NULL,
    entered_at timestamp(6) without time zone NOT NULL,
    entered_by character varying(100),
    remark_text text,
    remark_type character varying(20) NOT NULL,
    school_id bigint NOT NULL,
    session character varying(20) NOT NULL,
    student_id character varying(30) NOT NULL,
    template_id bigint NOT NULL
);


--
-- Name: report_card_remark_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_card_remark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_card_remark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_card_template; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_card_template (
    id bigint NOT NULL,
    assessment_group_id bigint NOT NULL,
    branding_json text,
    created_at timestamp(6) without time zone,
    description character varying(255),
    grading_override character varying(20),
    is_active boolean NOT NULL,
    is_default boolean NOT NULL,
    name character varying(255) NOT NULL,
    school_id bigint NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: report_card_template_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_card_template ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_card_template_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_card_template_section; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_card_template_section (
    id bigint NOT NULL,
    config_json text,
    display_order integer NOT NULL,
    enabled boolean NOT NULL,
    section_type character varying(50) NOT NULL,
    template_id bigint NOT NULL
);


--
-- Name: report_card_template_section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report_card_template_section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_card_template_section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permission (
    id bigint NOT NULL,
    role character varying(20) NOT NULL,
    school_id bigint,
    permission_key character varying(60) NOT NULL
);


--
-- Name: role_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.role_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.role_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school (
    id bigint NOT NULL,
    active boolean NOT NULL,
    address text,
    board_type character varying(20),
    city character varying(100),
    contact_person_name character varying(255),
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(255),
    expiry_date date,
    logo_url character varying(255),
    max_students integer,
    name character varying(255) NOT NULL,
    onboarded_by character varying(255),
    phone character varying(20),
    pincode character varying(10),
    plan character varying(20) NOT NULL,
    razorpay_key_id character varying(255),
    razorpay_key_secret character varying(255),
    slug character varying(255) NOT NULL,
    state character varying(100),
    theme_color character varying(20),
    website character varying(255),
    grading_system character varying(20),
    working_days character varying(100),
    academic_year_start_month integer NOT NULL,
    periods_per_day integer NOT NULL,
    checkin_window_end time(6) without time zone,
    checkin_window_start time(6) without time zone,
    geofence_radius integer,
    late_threshold_minutes integer,
    school_latitude double precision,
    school_longitude double precision,
    school_start_time time(6) without time zone,
    affiliation_number character varying(100),
    report_card_header_image_url character varying(500),
    school_code character varying(50),
    CONSTRAINT school_board_type_check CHECK (((board_type)::text = ANY ((ARRAY['CBSE'::character varying, 'ICSE'::character varying, 'STATE'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT school_plan_check CHECK (((plan)::text = ANY ((ARRAY['TRIAL'::character varying, 'BASIC'::character varying, 'PROFESSIONAL'::character varying, 'ENTERPRISE'::character varying])::text[])))
);


--
-- Name: school_class; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_class (
    id bigint NOT NULL,
    active boolean NOT NULL,
    display_order integer,
    name character varying(100) NOT NULL,
    school_id bigint NOT NULL,
    stream_eligible boolean NOT NULL
);


--
-- Name: school_class_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_class ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_class_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_effective_entitlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_effective_entitlements (
    school_id bigint NOT NULL,
    entitlement_source character varying(30),
    expires_at timestamp(6) without time zone,
    grace_ends_at timestamp(6) without time zone,
    last_rebuilt_at timestamp(6) without time zone,
    max_staff integer,
    max_students integer,
    plan_id bigint,
    plan_name character varying(200),
    plan_tier character varying(50),
    plan_version character varying(20),
    rebuilt_by character varying(50),
    resolved_priority_score integer,
    staff_hard_limit_pct integer,
    staff_soft_limit_pct integer,
    storage_gb_limit integer,
    storage_hard_limit_pct integer,
    storage_soft_limit_pct integer,
    student_hard_limit_pct integer,
    student_soft_limit_pct integer,
    subscription_status character varying(20),
    trial_ends_at timestamp(6) without time zone
);


--
-- Name: school_entitlement_features; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_entitlement_features (
    feature_key character varying(60) NOT NULL,
    school_id bigint NOT NULL,
    added_at timestamp(6) without time zone NOT NULL,
    source_plan_id bigint
);


--
-- Name: school_feature_overrides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_feature_overrides (
    feature_key character varying(60) NOT NULL,
    school_id bigint NOT NULL,
    override_state character varying(20) NOT NULL,
    updated_at timestamp(6) without time zone,
    updated_by character varying(100)
);


--
-- Name: school_holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_holidays (
    id bigint NOT NULL,
    academic_year character varying(20),
    affects_all boolean NOT NULL,
    start_date date NOT NULL,
    holiday_type character varying(30),
    name character varying(255) NOT NULL,
    school_id bigint NOT NULL,
    end_date date NOT NULL
);


--
-- Name: school_holidays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_holidays ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_holidays_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_subscription_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_subscription_history (
    id bigint NOT NULL,
    event_type character varying(40) NOT NULL,
    notes character varying(500),
    occurred_at timestamp(6) without time zone NOT NULL,
    performed_by character varying(100),
    plan_id bigint,
    plan_name character varying(200),
    school_id bigint NOT NULL,
    status character varying(20)
);


--
-- Name: school_subscription_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_subscription_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_subscription_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_subscriptions (
    id bigint NOT NULL,
    activated_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone NOT NULL,
    created_by character varying(100),
    expires_at timestamp(6) without time zone,
    grace_ends_at timestamp(6) without time zone,
    notes character varying(500),
    plan_id bigint NOT NULL,
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    trial_ends_at timestamp(6) without time zone,
    trial_start_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);


--
-- Name: school_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: section; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.section (
    id bigint NOT NULL,
    active boolean NOT NULL,
    class_id bigint NOT NULL,
    display_order integer,
    name character varying(50) NOT NULL,
    school_id bigint NOT NULL
);


--
-- Name: section_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.section ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.section_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stream_core_subject; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stream_core_subject (
    id bigint NOT NULL,
    school_id bigint,
    stream_id bigint NOT NULL,
    subject_name character varying(255) NOT NULL
);


--
-- Name: stream_core_subject_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stream_core_subject ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stream_core_subject_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student (
    student_id character varying(50) NOT NULL,
    class_name character varying(50),
    created_at timestamp(6) without time zone,
    distance double precision,
    dob date,
    email character varying(255),
    father_name character varying(200),
    gender character varying(10),
    joining_date date,
    leaving_date date,
    mother_name character varying(200),
    name character varying(200),
    phone_number character varying(20),
    photo_url character varying(255),
    school_id bigint,
    status character varying(255),
    takes_bus boolean,
    updated_at timestamp(6) without time zone,
    class_id bigint,
    section_id bigint,
    section_name character varying(50),
    conduct_at_leaving character varying(100),
    exit_remarks character varying(1000),
    reason_for_leaving character varying(500),
    CONSTRAINT student_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'UPCOMING'::character varying])::text[])))
);


--
-- Name: student_elective_enrollment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_elective_enrollment (
    id bigint NOT NULL,
    class_name character varying(255) NOT NULL,
    optional_group character varying(255) NOT NULL,
    school_id bigint NOT NULL,
    student_id character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL
);


--
-- Name: student_elective_enrollment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_elective_enrollment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_elective_enrollment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_fee_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_fee_config (
    id bigint NOT NULL,
    approved_by character varying(100),
    config_type character varying(20) NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    reason character varying(500),
    school_id bigint NOT NULL,
    student_id character varying(50) NOT NULL,
    valid_from date,
    valid_until date,
    value numeric(15,2),
    academic_session_id bigint NOT NULL,
    fee_head_id bigint NOT NULL,
    CONSTRAINT student_fee_config_config_type_check CHECK (((config_type)::text = ANY ((ARRAY['DISCOUNT_PERCENT'::character varying, 'DISCOUNT_FIXED'::character varying, 'WAIVER'::character varying, 'CUSTOM_AMOUNT'::character varying, 'OPT_OUT'::character varying])::text[])))
);


--
-- Name: student_fee_config_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_fee_config ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_fee_config_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_fees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_fees (
    id bigint NOT NULL,
    amount_paid numeric(38,2),
    class_name character varying(255),
    distance double precision,
    manual_payment_received numeric(38,2),
    manually_paid boolean,
    month integer,
    paid boolean,
    school_id bigint,
    student_id character varying(255),
    takes_bus boolean,
    year character varying(255),
    class_id bigint
);


--
-- Name: student_fees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_fees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_fees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_mark; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_mark (
    id bigint NOT NULL,
    entered_by character varying(255),
    exam_subject_entry_id bigint NOT NULL,
    marks_obtained double precision,
    school_id bigint,
    student_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: student_mark_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_mark ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_mark_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_stream_selection; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_stream_selection (
    id bigint NOT NULL,
    optional_subject_id bigint,
    school_id bigint,
    stream_id bigint NOT NULL,
    student_id character varying(255) NOT NULL
);


--
-- Name: student_stream_selection_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_stream_selection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_stream_selection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: teacher; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher (
    teacher_id character varying(255) NOT NULL,
    class_teacher character varying(255),
    created_at timestamp(6) without time zone,
    dob date,
    email character varying(255),
    gender character varying(255),
    joining_date date,
    name character varying(255),
    phone_number character varying(255),
    photo_url character varying(255),
    school_id bigint,
    updated_at timestamp(6) without time zone
);


--
-- Name: teacher_attendance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_attendance (
    id bigint NOT NULL,
    check_in_time timestamp(6) without time zone,
    check_out_time timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    date date NOT NULL,
    distance_from_school double precision,
    latitude double precision,
    longitude double precision,
    marked_by_admin boolean,
    method character varying(20),
    school_id bigint NOT NULL,
    status character varying(20) NOT NULL,
    teacher_id character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone
);


--
-- Name: teacher_attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: timetable_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.timetable_entry (
    id bigint NOT NULL,
    class_name character varying(255) NOT NULL,
    day character varying(255) NOT NULL,
    end_time character varying(255) NOT NULL,
    period_number integer NOT NULL,
    school_id bigint,
    start_time character varying(255) NOT NULL,
    subject_name character varying(255) NOT NULL,
    teacher_id character varying(255),
    teacher_name character varying(255),
    class_id bigint,
    section_id bigint,
    section_name character varying(50),
    CONSTRAINT timetable_entry_day_check CHECK (((day)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying])::text[])))
);


--
-- Name: timetable_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.timetable_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.timetable_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    school_id bigint,
    user_id character varying(255) NOT NULL,
    notification_id bigint NOT NULL
);


--
-- Name: user_notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.user_notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255),
    password character varying(255),
    reset_token character varying(100),
    reset_token_expiry timestamp(6) without time zone,
    role character varying(20),
    school_id bigint,
    user_id character varying(100),
    refresh_token_id character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: academic_session academic_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_session
    ADD CONSTRAINT academic_session_pkey PRIMARY KEY (id);


--
-- Name: academic_stream academic_stream_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_stream
    ADD CONSTRAINT academic_stream_pkey PRIMARY KEY (id);


--
-- Name: admin admin_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin
    ADD CONSTRAINT admin_pkey PRIMARY KEY (admin_id);


--
-- Name: ai_fee_reminder_batch ai_fee_reminder_batch_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_fee_reminder_batch
    ADD CONSTRAINT ai_fee_reminder_batch_pkey PRIMARY KEY (id);


--
-- Name: ai_trace_event ai_trace_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_trace_event
    ADD CONSTRAINT ai_trace_event_pkey PRIMARY KEY (id);


--
-- Name: assessment_group_composition assessment_group_composition_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_group_composition
    ADD CONSTRAINT assessment_group_composition_pkey PRIMARY KEY (id);


--
-- Name: assessment_group_exam_mapping assessment_group_exam_mapping_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_group_exam_mapping
    ADD CONSTRAINT assessment_group_exam_mapping_pkey PRIMARY KEY (id);


--
-- Name: assessment_group assessment_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_group
    ADD CONSTRAINT assessment_group_pkey PRIMARY KEY (id);


--
-- Name: assessment_group_result assessment_group_result_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.assessment_group_result
    ADD CONSTRAINT assessment_group_result_pkey PRIMARY KEY (id);


--
-- Name: attendance attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);


--
-- Name: audit_log_archive audit_log_archive_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log_archive
    ADD CONSTRAINT audit_log_archive_pkey PRIMARY KEY (id);


--
-- Name: audit_log audit_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_log
    ADD CONSTRAINT audit_log_pkey PRIMARY KEY (id);


--
-- Name: bus_fees bus_fees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bus_fees
    ADD CONSTRAINT bus_fees_pkey PRIMARY KEY (id);


--
-- Name: class_subject class_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_subject
    ADD CONSTRAINT class_subject_pkey PRIMARY KEY (id);


--
-- Name: co_scholastic_entry co_scholastic_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.co_scholastic_entry
    ADD CONSTRAINT co_scholastic_entry_pkey PRIMARY KEY (id);


--
-- Name: credit_note credit_note_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_note
    ADD CONSTRAINT credit_note_pkey PRIMARY KEY (id);


--
-- Name: demo_requests demo_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.demo_requests
    ADD CONSTRAINT demo_requests_pkey PRIMARY KEY (id);


--
-- Name: device_tokens device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: exam_config exam_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_config
    ADD CONSTRAINT exam_config_pkey PRIMARY KEY (id);


--
-- Name: exam_subject_entry exam_subject_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_subject_entry
    ADD CONSTRAINT exam_subject_entry_pkey PRIMARY KEY (id);


--
-- Name: feature_catalog feature_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_catalog
    ADD CONSTRAINT feature_catalog_pkey PRIMARY KEY (feature_key);


--
-- Name: fee_head fee_head_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_head
    ADD CONSTRAINT fee_head_pkey PRIMARY KEY (id);


--
-- Name: fee_payment fee_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_payment
    ADD CONSTRAINT fee_payment_pkey PRIMARY KEY (id);


--
-- Name: fee_structure fee_structure_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure
    ADD CONSTRAINT fee_structure_pkey PRIMARY KEY (id);


--
-- Name: fee_structure_rule fee_structure_rule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_rule
    ADD CONSTRAINT fee_structure_rule_pkey PRIMARY KEY (id);


--
-- Name: global_subscription_config global_subscription_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.global_subscription_config
    ADD CONSTRAINT global_subscription_config_pkey PRIMARY KEY (config_id);


--
-- Name: invoice_line_item invoice_line_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_line_item
    ADD CONSTRAINT invoice_line_item_pkey PRIMARY KEY (id);


--
-- Name: invoice invoice_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT invoice_pkey PRIMARY KEY (id);


--
-- Name: knowledge_chunk knowledge_chunk_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_chunk
    ADD CONSTRAINT knowledge_chunk_pkey PRIMARY KEY (id);


--
-- Name: knowledge_document knowledge_document_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.knowledge_document
    ADD CONSTRAINT knowledge_document_pkey PRIMARY KEY (id);


--
-- Name: leaves leaves_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.leaves
    ADD CONSTRAINT leaves_pkey PRIMARY KEY (id);


--
-- Name: notification_channels notification_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_channels
    ADD CONSTRAINT notification_channels_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: optional_subject_group optional_subject_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.optional_subject_group
    ADD CONSTRAINT optional_subject_group_pkey PRIMARY KEY (id);


--
-- Name: optional_subject optional_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.optional_subject
    ADD CONSTRAINT optional_subject_pkey PRIMARY KEY (id);


--
-- Name: payment_allocation payment_allocation_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_allocation
    ADD CONSTRAINT payment_allocation_pkey PRIMARY KEY (id);


--
-- Name: payment payment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment
    ADD CONSTRAINT payment_pkey PRIMARY KEY (id);


--
-- Name: permission permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permission
    ADD CONSTRAINT permission_pkey PRIMARY KEY (permission_key);


--
-- Name: plan_feature_changes plan_feature_changes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_feature_changes
    ADD CONSTRAINT plan_feature_changes_pkey PRIMARY KEY (id);


--
-- Name: plan_features plan_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plan_features
    ADD CONSTRAINT plan_features_pkey PRIMARY KEY (feature_key, plan_id);


--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);


--
-- Name: report_card_publication report_card_publication_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_publication
    ADD CONSTRAINT report_card_publication_pkey PRIMARY KEY (id);


--
-- Name: report_card_remark report_card_remark_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_remark
    ADD CONSTRAINT report_card_remark_pkey PRIMARY KEY (id);


--
-- Name: report_card_template report_card_template_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_template
    ADD CONSTRAINT report_card_template_pkey PRIMARY KEY (id);


--
-- Name: report_card_template_section report_card_template_section_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_template_section
    ADD CONSTRAINT report_card_template_section_pkey PRIMARY KEY (id);


--
-- Name: role_permission role_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT role_permission_pkey PRIMARY KEY (id);


--
-- Name: school_class school_class_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_class
    ADD CONSTRAINT school_class_pkey PRIMARY KEY (id);


--
-- Name: school_effective_entitlements school_effective_entitlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_effective_entitlements
    ADD CONSTRAINT school_effective_entitlements_pkey PRIMARY KEY (school_id);


--
-- Name: school_entitlement_features school_entitlement_features_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_entitlement_features
    ADD CONSTRAINT school_entitlement_features_pkey PRIMARY KEY (feature_key, school_id);


--
-- Name: school_feature_overrides school_feature_overrides_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_feature_overrides
    ADD CONSTRAINT school_feature_overrides_pkey PRIMARY KEY (feature_key, school_id);


--
-- Name: school_holidays school_holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_holidays
    ADD CONSTRAINT school_holidays_pkey PRIMARY KEY (id);


--
-- Name: school school_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT school_pkey PRIMARY KEY (id);


--
-- Name: school_subscription_history school_subscription_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_subscription_history
    ADD CONSTRAINT school_subscription_history_pkey PRIMARY KEY (id);


--
-- Name: school_subscriptions school_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_subscriptions
    ADD CONSTRAINT school_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: section section_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section
    ADD CONSTRAINT section_pkey PRIMARY KEY (id);


--
-- Name: stream_core_subject stream_core_subject_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stream_core_subject
    ADD CONSTRAINT stream_core_subject_pkey PRIMARY KEY (id);


--
-- Name: student_elective_enrollment student_elective_enrollment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_elective_enrollment
    ADD CONSTRAINT student_elective_enrollment_pkey PRIMARY KEY (id);


--
-- Name: student_fee_config student_fee_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_fee_config
    ADD CONSTRAINT student_fee_config_pkey PRIMARY KEY (id);


--
-- Name: student_fees student_fees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_fees
    ADD CONSTRAINT student_fees_pkey PRIMARY KEY (id);


--
-- Name: student_mark student_mark_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_mark
    ADD CONSTRAINT student_mark_pkey PRIMARY KEY (id);


--
-- Name: student student_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student
    ADD CONSTRAINT student_pkey PRIMARY KEY (student_id);


--
-- Name: student_stream_selection student_stream_selection_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_stream_selection
    ADD CONSTRAINT student_stream_selection_pkey PRIMARY KEY (id);


--
-- Name: teacher_attendance teacher_attendance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_attendance
    ADD CONSTRAINT teacher_attendance_pkey PRIMARY KEY (id);


--
-- Name: teacher teacher_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher
    ADD CONSTRAINT teacher_pkey PRIMARY KEY (teacher_id);


--
-- Name: timetable_entry timetable_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.timetable_entry
    ADD CONSTRAINT timetable_entry_pkey PRIMARY KEY (id);


--
-- Name: notification_channels uk4qjnityt1uqbmcph0d9ribtq0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_channels
    ADD CONSTRAINT uk4qjnityt1uqbmcph0d9ribtq0 UNIQUE (school_id, channel_type);


--
-- Name: users uk6efs5vmce86ymf5q7lmvn2uuf; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6efs5vmce86ymf5q7lmvn2uuf UNIQUE (user_id);


--
-- Name: student_stream_selection uk7c1a4kc167abjrsptxb2k73ml; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_stream_selection
    ADD CONSTRAINT uk7c1a4kc167abjrsptxb2k73ml UNIQUE (student_id);


--
-- Name: device_tokens uk8se1i37nto56x9252rmrit8ib; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT uk8se1i37nto56x9252rmrit8ib UNIQUE (token);


--
-- Name: school_subscriptions uk_school_subscription; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_subscriptions
    ADD CONSTRAINT uk_school_subscription UNIQUE (school_id);


--
-- Name: stream_core_subject ukdaqljtr6oum6yxnm19kprkgbu; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stream_core_subject
    ADD CONSTRAINT ukdaqljtr6oum6yxnm19kprkgbu UNIQUE (stream_id, subject_name);


--
-- Name: student_mark ukg0ecx040m5jqqkebmryb90jw3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_mark
    ADD CONSTRAINT ukg0ecx040m5jqqkebmryb90jw3 UNIQUE (student_id, exam_subject_entry_id);


--
-- Name: report_card_publication uklwsnlc31bo6o2knn7l7vswhwh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_publication
    ADD CONSTRAINT uklwsnlc31bo6o2knn7l7vswhwh UNIQUE (verification_token);


--
-- Name: ai_fee_reminder_batch ukmfsuneihib5ga12si6xcp3vqd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_fee_reminder_batch
    ADD CONSTRAINT ukmfsuneihib5ga12si6xcp3vqd UNIQUE (workflow_id);


--
-- Name: exam_config uknysqeyvylll8i8xcqcl3ti2i3; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_config
    ADD CONSTRAINT uknysqeyvylll8i8xcqcl3ti2i3 UNIQUE (session, class_name, exam_name);


--
-- Name: school_holidays ukps4jj0sspkstjtwo95nu8a9jc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_holidays
    ADD CONSTRAINT ukps4jj0sspkstjtwo95nu8a9jc UNIQUE (school_id, start_date);


--
-- Name: exam_subject_entry ukpt3821q5ksk31l8dh0n4faoda; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exam_subject_entry
    ADD CONSTRAINT ukpt3821q5ksk31l8dh0n4faoda UNIQUE (exam_config_id, subject_name);


--
-- Name: student_elective_enrollment ukqn73n2oh1oqn5keodobe6wc6w; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_elective_enrollment
    ADD CONSTRAINT ukqn73n2oh1oqn5keodobe6wc6w UNIQUE (school_id, student_id, class_name, optional_group);


--
-- Name: class_subject uktgbvi51if9cyreqll0yem061s; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class_subject
    ADD CONSTRAINT uktgbvi51if9cyreqll0yem061s UNIQUE (class_name, subject_name);


--
-- Name: fee_head uq_fee_head_school_code; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_head
    ADD CONSTRAINT uq_fee_head_school_code UNIQUE (school_id, code);


--
-- Name: fee_structure_rule uq_fsr_school_session_class_feehead; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_rule
    ADD CONSTRAINT uq_fsr_school_session_class_feehead UNIQUE (school_id, academic_session_id, class_name, fee_head_id);


--
-- Name: invoice uq_invoice_number_school; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT uq_invoice_number_school UNIQUE (school_id, invoice_number);


--
-- Name: payment_allocation uq_payment_invoice; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_allocation
    ADD CONSTRAINT uq_payment_invoice UNIQUE (fee_payment_id, invoice_id);


--
-- Name: report_card_publication uq_pub; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_card_publication
    ADD CONSTRAINT uq_pub UNIQUE (school_id, template_id, session, class_name);


--
-- Name: role_permission uq_role_permission; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT uq_role_permission UNIQUE (role, permission_key, school_id);


--
-- Name: school_class uq_school_class_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_class
    ADD CONSTRAINT uq_school_class_name UNIQUE (school_id, name);


--
-- Name: school uq_school_slug; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school
    ADD CONSTRAINT uq_school_slug UNIQUE (slug);


--
-- Name: section uq_section_class_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.section
    ADD CONSTRAINT uq_section_class_name UNIQUE (school_id, class_id, name);


--
-- Name: academic_session uq_session_school_label; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.academic_session
    ADD CONSTRAINT uq_session_school_label UNIQUE (school_id, label);


--
-- Name: teacher_attendance uq_teacher_date_school; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_attendance
    ADD CONSTRAINT uq_teacher_date_school UNIQUE (teacher_id, date, school_id);


--
-- Name: user_notifications user_notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT user_notifications_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_ai_fee_reminder_batch_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_fee_reminder_batch_school ON public.ai_fee_reminder_batch USING btree (school_id);


--
-- Name: idx_ai_trace_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trace_created_at ON public.ai_trace_event USING btree (created_at);


--
-- Name: idx_ai_trace_school_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trace_school_id ON public.ai_trace_event USING btree (school_id);


--
-- Name: idx_ai_trace_trace_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_trace_trace_id ON public.ai_trace_event USING btree (trace_id);


--
-- Name: idx_attendance_class_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attendance_class_date ON public.attendance USING btree (class_name, date);


--
-- Name: idx_attendance_student_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_attendance_student_date ON public.attendance USING btree (student_id, date);


--
-- Name: idx_audit_log_timestamp; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_log_timestamp ON public.audit_log USING btree ("timestamp");


--
-- Name: idx_cn_student_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_cn_student_school ON public.credit_note USING btree (school_id, student_id);


--
-- Name: idx_device_tokens_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_tokens_user_id ON public.device_tokens USING btree (user_id);


--
-- Name: idx_fp_razorpay_order; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fp_razorpay_order ON public.fee_payment USING btree (razorpay_order_id);


--
-- Name: idx_fp_student_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fp_student_school ON public.fee_payment USING btree (school_id, student_id);


--
-- Name: idx_fsr_school_session_class; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_fsr_school_session_class ON public.fee_structure_rule USING btree (school_id, academic_session_id, class_name);


--
-- Name: idx_holiday_school_end; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_holiday_school_end ON public.school_holidays USING btree (school_id, end_date);


--
-- Name: idx_holiday_school_start; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_holiday_school_start ON public.school_holidays USING btree (school_id, start_date);


--
-- Name: idx_invoice_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invoice_status ON public.invoice USING btree (school_id, status);


--
-- Name: idx_invoice_student_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_invoice_student_session ON public.invoice USING btree (school_id, student_id, academic_session_id);


--
-- Name: idx_knowledge_chunk_document; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_knowledge_chunk_document ON public.knowledge_chunk USING btree (document_id);


--
-- Name: idx_knowledge_chunk_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_knowledge_chunk_school ON public.knowledge_chunk USING btree (school_id);


--
-- Name: idx_knowledge_document_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_knowledge_document_school ON public.knowledge_document USING btree (school_id);


--
-- Name: idx_leaves_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_leaves_status ON public.leaves USING btree (status);


--
-- Name: idx_leaves_student_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_leaves_student_id ON public.leaves USING btree (student_id);


--
-- Name: idx_notifications_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at);


--
-- Name: idx_notifications_created_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_created_by ON public.notifications USING btree (created_by);


--
-- Name: idx_payment_student_session_month; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_payment_student_session_month ON public.payment USING btree (student_id, session, month);


--
-- Name: idx_pfc_plan_feature; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pfc_plan_feature ON public.plan_feature_changes USING btree (plan_id, feature_key);


--
-- Name: idx_sfc_student_session; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sfc_student_session ON public.student_fee_config USING btree (school_id, student_id, academic_session_id);


--
-- Name: idx_student_class_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_class_status ON public.student USING btree (class_name, status);


--
-- Name: idx_student_fees_student_year_month; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_student_fees_student_year_month ON public.student_fees USING btree (student_id, year, month);


--
-- Name: idx_sub_history_school; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sub_history_school ON public.school_subscription_history USING btree (school_id);


--
-- Name: idx_teacher_att_school_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_teacher_att_school_date ON public.teacher_attendance USING btree (school_id, date);


--
-- Name: idx_teacher_att_teacher_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_teacher_att_teacher_date ON public.teacher_attendance USING btree (teacher_id, date);


--
-- Name: idx_user_notifications_user_read; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_notifications_user_read ON public.user_notifications USING btree (user_id, is_read);


--
-- Name: feature_catalog_dependencies fk2u3x7d5i3t6m0d5th0fiubwn7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.feature_catalog_dependencies
    ADD CONSTRAINT fk2u3x7d5i3t6m0d5th0fiubwn7 FOREIGN KEY (feature_key) REFERENCES public.feature_catalog(feature_key);


--
-- Name: payment_allocation fk3avpuh81jy30xuy94ox81u16q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_allocation
    ADD CONSTRAINT fk3avpuh81jy30xuy94ox81u16q FOREIGN KEY (invoice_id) REFERENCES public.invoice(id);


--
-- Name: invoice_line_item fk4560gqjs1jn62cp4govj4akb3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_line_item
    ADD CONSTRAINT fk4560gqjs1jn62cp4govj4akb3 FOREIGN KEY (invoice_id) REFERENCES public.invoice(id);


--
-- Name: role_permission fk50lb4oc8yb4jh778o6ybool5; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permission
    ADD CONSTRAINT fk50lb4oc8yb4jh778o6ybool5 FOREIGN KEY (permission_key) REFERENCES public.permission(permission_key);


--
-- Name: payment_allocation fk5qogdx3swvlt4rfuf90q9uayl; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payment_allocation
    ADD CONSTRAINT fk5qogdx3swvlt4rfuf90q9uayl FOREIGN KEY (fee_payment_id) REFERENCES public.fee_payment(id);


--
-- Name: credit_note fk89mv8mrynbjxoc6khjkbfibeb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.credit_note
    ADD CONSTRAINT fk89mv8mrynbjxoc6khjkbfibeb FOREIGN KEY (invoice_id) REFERENCES public.invoice(id);


--
-- Name: event_target_audience fk8kracchrgdrj5b1afs78i9uuf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_target_audience
    ADD CONSTRAINT fk8kracchrgdrj5b1afs78i9uuf FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: invoice_line_item fkefyv0okl7xhygecpmmixcnet1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice_line_item
    ADD CONSTRAINT fkefyv0okl7xhygecpmmixcnet1 FOREIGN KEY (fee_head_id) REFERENCES public.fee_head(id);


--
-- Name: student_fee_config fkfrnt3qrqkh9evp85ib98hqsyu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_fee_config
    ADD CONSTRAINT fkfrnt3qrqkh9evp85ib98hqsyu FOREIGN KEY (academic_session_id) REFERENCES public.academic_session(id);


--
-- Name: invoice fkh6pk1b4q7sy9qp1p5rhd944od; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.invoice
    ADD CONSTRAINT fkh6pk1b4q7sy9qp1p5rhd944od FOREIGN KEY (academic_session_id) REFERENCES public.academic_session(id);


--
-- Name: student_fee_config fkmfx51dmx5jx311xq7os90i577; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_fee_config
    ADD CONSTRAINT fkmfx51dmx5jx311xq7os90i577 FOREIGN KEY (fee_head_id) REFERENCES public.fee_head(id);


--
-- Name: event_video_links fkmkh9897pnxs7h274ejnhbetf2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_video_links
    ADD CONSTRAINT fkmkh9897pnxs7h274ejnhbetf2 FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: fee_structure_rule fknhks7dl5irmgyg8acew25qgcm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_rule
    ADD CONSTRAINT fknhks7dl5irmgyg8acew25qgcm FOREIGN KEY (fee_head_id) REFERENCES public.fee_head(id);


--
-- Name: user_notifications fkovvx0ab3h8s9lrm6fppuadn7d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notifications
    ADD CONSTRAINT fkovvx0ab3h8s9lrm6fppuadn7d FOREIGN KEY (notification_id) REFERENCES public.notifications(id);


--
-- Name: fee_structure_rule fkt4mniyjs9crevk5dryndo2ppe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fee_structure_rule
    ADD CONSTRAINT fkt4mniyjs9crevk5dryndo2ppe FOREIGN KEY (academic_session_id) REFERENCES public.academic_session(id);


--
-- PostgreSQL database dump complete
--


