ALTER TABLE notifications
    ADD COLUMN IF NOT EXISTS event_code VARCHAR(80),
    ADD COLUMN IF NOT EXISTS category VARCHAR(40),
    ADD COLUMN IF NOT EXISTS priority VARCHAR(20),
    ADD COLUMN IF NOT EXISTS source_entity_type VARCHAR(80),
    ADD COLUMN IF NOT EXISTS source_entity_id VARCHAR(255),
    ADD COLUMN IF NOT EXISTS action_route VARCHAR(500),
    ADD COLUMN IF NOT EXISTS action_metadata TEXT,
    ADD COLUMN IF NOT EXISTS actor_user_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP WITHOUT TIME ZONE,
    ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(180);

UPDATE notifications
SET event_code = CASE
        WHEN UPPER(COALESCE(type, '')) = 'NOTICE' THEN 'NOTICE_PUBLISHED'
        ELSE 'LEGACY_NOTIFICATION'
    END,
    category = CASE
        WHEN UPPER(COALESCE(type, '')) = 'NOTICE' THEN 'NOTICE_ANNOUNCEMENT'
        WHEN UPPER(COALESCE(type, '')) LIKE '%LEAVE%' THEN 'LEAVE'
        WHEN UPPER(COALESCE(type, '')) LIKE '%FEE%' OR UPPER(COALESCE(type, '')) LIKE '%PAYMENT%' THEN 'FEES_PAYMENTS'
        WHEN UPPER(COALESCE(type, '')) LIKE '%ATTENDANCE%' THEN 'ATTENDANCE'
        ELSE 'SYSTEM_ADMIN'
    END,
    priority = 'NORMAL'
WHERE event_code IS NULL OR category IS NULL OR priority IS NULL;

ALTER TABLE notifications
    ALTER COLUMN event_code SET NOT NULL,
    ALTER COLUMN category SET NOT NULL,
    ALTER COLUMN priority SET NOT NULL;

ALTER TABLE user_notifications ADD COLUMN IF NOT EXISTS read_at TIMESTAMP WITHOUT TIME ZONE;
UPDATE user_notifications SET read_at = COALESCE(read_at, created_at)
WHERE is_read = TRUE AND read_at IS NULL;

CREATE TABLE IF NOT EXISTS notification_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    user_notification_id BIGINT NOT NULL REFERENCES user_notifications(id) ON DELETE CASCADE,
    recipient_user_id VARCHAR(100) NOT NULL,
    channel VARCHAR(20) NOT NULL,
    destination VARCHAR(320),
    status VARCHAR(30) NOT NULL,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    next_attempt_at TIMESTAMP WITHOUT TIME ZONE,
    last_error TEXT,
    provider_message_id VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sent_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT uq_notification_delivery_recipient_channel
        UNIQUE (school_id, user_notification_id, channel),
    CONSTRAINT ck_notification_delivery_channel CHECK (channel IN ('PUSH', 'EMAIL')),
    CONSTRAINT ck_notification_delivery_status CHECK
        (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED_RETRYABLE', 'FAILED_FINAL', 'SKIPPED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_tenant_idempotency
    ON notifications (school_id, idempotency_key)
    WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uq_notifications_global_idempotency
    ON notifications (idempotency_key)
    WHERE school_id IS NULL AND idempotency_key IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_notifications_inbox
    ON user_notifications (school_id, user_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_user_notifications_unread
    ON user_notifications (school_id, user_id)
    WHERE is_read = FALSE;
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_pending
    ON notification_deliveries (status, next_attempt_at, id);
CREATE INDEX IF NOT EXISTS idx_notification_deliveries_notification
    ON notification_deliveries (school_id, notification_id);
