-- Phase A: authoritative, session-bound student class/section membership.
-- No rows are backfilled here. Existing Student live class/section columns remain unchanged.

-- btree_gist is available on the DEV Neon PostgreSQL database and the migration user has
-- CREATE privilege. It lets scalar tenant/student/session keys participate in the same
-- exclusion constraint as the enrollment date range.
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Composite candidate keys are required by the tenant-safe foreign keys below. The existing
-- single-column primary keys remain unchanged. DEV preflight found no duplicate groups.
ALTER TABLE student
    ADD CONSTRAINT uq_student_school_student_id UNIQUE (school_id, student_id);

ALTER TABLE academic_session
    ADD CONSTRAINT uq_academic_session_school_id UNIQUE (school_id, id);

ALTER TABLE school_class
    ADD CONSTRAINT uq_school_class_school_id UNIQUE (school_id, id);

ALTER TABLE section
    ADD CONSTRAINT uq_section_school_id_class_id UNIQUE (school_id, id, class_id);

CREATE TABLE student_enrollment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    student_id VARCHAR(50) NOT NULL,
    academic_session_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    class_name_snapshot VARCHAR(100) NOT NULL,
    section_id BIGINT,
    section_name_snapshot VARCHAR(50),
    status VARCHAR(20) NOT NULL,
    effective_from DATE NOT NULL,
    effective_until DATE,
    closure_reason VARCHAR(30),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT ck_student_enrollment_status CHECK
        (status IN ('PLANNED', 'ACTIVE', 'CLOSED', 'CANCELLED')),
    CONSTRAINT ck_student_enrollment_closure_reason CHECK
        (closure_reason IS NULL OR closure_reason IN
            ('SESSION_COMPLETED', 'CLASS_CHANGE', 'SECTION_CHANGE', 'GRADUATED',
             'TRANSFERRED', 'WITHDRAWN', 'CANCELLED_BEFORE_START')),
    CONSTRAINT ck_student_enrollment_date_range CHECK
        (effective_until IS NULL OR effective_until >= effective_from),
    CONSTRAINT ck_student_enrollment_lifecycle CHECK (
        (status IN ('PLANNED', 'ACTIVE') AND effective_until IS NULL AND closure_reason IS NULL)
        OR
        (status = 'CLOSED' AND effective_until IS NOT NULL
            AND closure_reason IS NOT NULL AND closure_reason <> 'CANCELLED_BEFORE_START')
        OR
        (status = 'CANCELLED' AND effective_until = effective_from
            AND closure_reason = 'CANCELLED_BEFORE_START')
    ),
    CONSTRAINT ck_student_enrollment_section_snapshot CHECK (
        (section_id IS NULL AND section_name_snapshot IS NULL)
        OR (section_id IS NOT NULL AND section_name_snapshot IS NOT NULL)
    ),

    CONSTRAINT fk_student_enrollment_school FOREIGN KEY (school_id)
        REFERENCES school (id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_enrollment_student FOREIGN KEY (school_id, student_id)
        REFERENCES student (school_id, student_id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_enrollment_session FOREIGN KEY (school_id, academic_session_id)
        REFERENCES academic_session (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_enrollment_class FOREIGN KEY (school_id, class_id)
        REFERENCES school_class (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_student_enrollment_section FOREIGN KEY (school_id, section_id, class_id)
        REFERENCES section (school_id, id, class_id) ON DELETE RESTRICT,

    CONSTRAINT uq_student_enrollment_segment_start
        UNIQUE (school_id, student_id, academic_session_id, effective_from),

    -- Business dates are inclusive: effective_from <= date <= effective_until.
    -- PostgreSQL canonicalizes daterange(from, until, '[]') to [from, until + 1), so a
    -- successor beginning the day after effective_until does not overlap. CANCELLED rows
    -- never represented membership and are intentionally excluded from temporal conflicts.
    CONSTRAINT ex_student_enrollment_no_overlap EXCLUDE USING gist (
        school_id WITH =,
        student_id WITH =,
        academic_session_id WITH =,
        daterange(effective_from, effective_until, '[]') WITH &&
    ) WHERE (status <> 'CANCELLED')
);

CREATE UNIQUE INDEX uq_student_enrollment_one_open
    ON student_enrollment (school_id, student_id, academic_session_id)
    WHERE status IN ('PLANNED', 'ACTIVE') AND effective_until IS NULL;

CREATE INDEX idx_student_enrollment_student_session
    ON student_enrollment (school_id, student_id, academic_session_id, effective_from);

CREATE INDEX idx_student_enrollment_session_roster
    ON student_enrollment (school_id, academic_session_id, class_id, section_id, status);

CREATE INDEX idx_student_enrollment_effective_dates
    ON student_enrollment (school_id, student_id, effective_from, effective_until);
