-- Phase F2: additive-only schema foundation for AcademicSession-scoped timetable/teaching
-- configuration (see F0/F1 audit). PROD evidence: timetable_entry has zero DB-level session
-- scoping and zero FK constraints today, and every one of its 640 existing rows has
-- class_id/section_id = NULL (only the denormalized class_name/section_name strings are
-- populated). This migration adds the session link and a new historical/future "who is
-- configured as class-teacher" table WITHOUT touching any existing row, WITHOUT backfilling,
-- and WITHOUT changing live teacher authorization — Teacher.classTeacher/classTeacherSectionId,
-- the only columns TeacherClassScopeService reads, are untouched. This table is configuration
-- evidence only, never an authorization source.

-- ── timetable_entry: additive session link, no uniqueness yet ──────────────────────────────
-- Nullable, no default: a pure metadata-only ADD COLUMN that does not rewrite existing rows.
-- Legacy rows keep NULL until an explicit, reviewed backfill (a later phase) assigns them —
-- never guessed here. Deliberately NOT adding any slot-uniqueness constraint in this migration:
-- every existing PROD row already has class_id = NULL, F3 has not yet established canonical
-- ID-based session-aware writes, and PostgreSQL's NULL-uniqueness semantics need the same
-- deliberate proof-via-integration-test treatment given to the two partial indexes below before
-- being applied to timetable_entry. That comes after F3 finalizes canonical class/section
-- representation there.
ALTER TABLE timetable_entry ADD COLUMN academic_session_id BIGINT NULL;

ALTER TABLE timetable_entry
    ADD CONSTRAINT fk_timetable_entry_session
    FOREIGN KEY (school_id, academic_session_id)
    REFERENCES academic_session (school_id, id)
    ON DELETE RESTRICT;

-- ── class_teacher_responsibility: new session-scoped configured-responsibility record ──────
-- Deliberately separate from Teacher.classTeacher/classTeacherSectionId (the LIVE authorization
-- projection) — this table is historical/future CONFIGURATION only and is never consulted for
-- authorization. No status/lifecycle column: challenged per F1 and rejected — a responsibility
-- change is a plain UPDATE (or replace) of the one row the two partial unique indexes below
-- already guarantee is singular per class/section per session; there is no state transition and
-- no query that would ever filter by a status, so a constant-value column was not added
-- speculatively.
CREATE TABLE class_teacher_responsibility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT,
    teacher_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_class_teacher_responsibility_session FOREIGN KEY (school_id, academic_session_id)
        REFERENCES academic_session (school_id, id) ON DELETE RESTRICT,
    CONSTRAINT fk_class_teacher_responsibility_class FOREIGN KEY (school_id, class_id)
        REFERENCES school_class (school_id, id) ON DELETE RESTRICT,
    -- section's own composite unique key is (school_id, id, class_id) — an FK must reference
    -- columns in that exact order, so the referencing columns are ordered to match (not
    -- school_id, class_id, section_id), the same pattern V53 already used for
    -- fk_student_enrollment_section. NULL section_id (sectionless class) skips this check
    -- entirely under MATCH SIMPLE, since school_id/class_id alone are never sufficient to
    -- satisfy a 3-column key — this is the deliberate "no section required" escape hatch.
    CONSTRAINT fk_class_teacher_responsibility_section FOREIGN KEY (school_id, section_id, class_id)
        REFERENCES section (school_id, id, class_id) ON DELETE RESTRICT,
    -- teacher.teacher_id is already globally unique (teacher_pkey is PRIMARY KEY (teacher_id)
    -- alone, no school_id in the key — confirmed against the actual PROD catalog, not assumed),
    -- so no composite key is needed for this FK.
    CONSTRAINT fk_class_teacher_responsibility_teacher FOREIGN KEY (teacher_id)
        REFERENCES teacher (teacher_id) ON DELETE RESTRICT
);

-- One class-teacher responsibility per class/section for now (approved product decision).
-- Two partial indexes, not one plain UNIQUE, because PostgreSQL treats every NULL as distinct:
-- a plain UNIQUE (school_id, academic_session_id, class_id, section_id) would silently allow
-- unlimited duplicate rows for every sectionless class.
CREATE UNIQUE INDEX uq_class_teacher_responsibility_no_section
    ON class_teacher_responsibility (school_id, academic_session_id, class_id)
    WHERE section_id IS NULL;

CREATE UNIQUE INDEX uq_class_teacher_responsibility_with_section
    ON class_teacher_responsibility (school_id, academic_session_id, class_id, section_id)
    WHERE section_id IS NOT NULL;

CREATE INDEX idx_class_teacher_responsibility_teacher
    ON class_teacher_responsibility (teacher_id, school_id);
