-- Phase F4.1: F4's activation preview conflated two different claims under one boolean —
-- "does live currently equal configured" (a coincidence that can be true even when nobody ever
-- activated the session) and "was this configuration ever explicitly applied." This migration
-- adds the minimum persisted state needed to tell them apart.
--
-- One row per (school, academic_session) — the LATEST successful apply only, not a revision
-- history. class_teacher_activation_log/audit_log already record every action generically for
-- audit purposes; this table exists purely so a fast, reliable "has this session's current
-- configuration actually been applied" check doesn't need to parse audit JSON blobs or infer
-- from timestamps (which concurrency can make unreliable) — it's a content comparison instead:
-- configuration_fingerprint is a SHA-256 of the exact set of (classId, sectionId, teacherId)
-- rows ClassTeacherActivationService actually applied, computed and stored in the SAME
-- transaction as the live Teacher writes (see ClassTeacherActivationService#apply). A later
-- read compares the CURRENT configuration's fingerprint against this stored one, plus a fresh
-- live-vs-configured comparison, to distinguish:
--   - no row at all                                    -> NEVER_APPLIED
--   - row exists, fingerprint matches, live in sync     -> APPLIED_IN_SYNC
--   - row exists, but fingerprint OR live has changed   -> APPLIED_BUT_DRIFTED
-- No trigger or hook is needed on responsibility/teacher writes to "invalidate" this row — the
-- comparison is recomputed fresh on every read, so it can never go stale in a way that matters.
CREATE TABLE class_teacher_activation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    configuration_fingerprint VARCHAR(64) NOT NULL,
    applied_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    applied_by VARCHAR(255),

    CONSTRAINT uq_class_teacher_activation_session UNIQUE (school_id, academic_session_id),
    CONSTRAINT fk_class_teacher_activation_session FOREIGN KEY (school_id, academic_session_id)
        REFERENCES academic_session (school_id, id) ON DELETE RESTRICT
);
