-- Optimistic revision detects any intervening timetable edit, including edits away and back.
ALTER TABLE timetable_entry ADD COLUMN revision BIGINT NOT NULL DEFAULT 0;
ALTER TABLE teacher ADD CONSTRAINT uq_teacher_correction_tenant UNIQUE (school_id, teacher_id);

CREATE TABLE timetable_correction_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    timetable_entry_id BIGINT,
    requested_by_teacher_id VARCHAR(255) NOT NULL,
    expected_current_teacher_id VARCHAR(255) NOT NULL,
    requested_teacher_id VARCHAR(255) NOT NULL,
    expected_revision BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    reason VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    reviewed_at TIMESTAMP WITHOUT TIME ZONE,
    reviewed_by VARCHAR(255),
    CHECK (requested_teacher_id = requested_by_teacher_id),
    CHECK (requested_teacher_id <> expected_current_teacher_id),
    FOREIGN KEY (school_id, academic_session_id) REFERENCES academic_session (school_id, id),
    -- Deliberately a single-column FK, not a (school_id, academic_session_id, timetable_entry_id)
    -- composite: a real PostgreSQL run proved that pairing a composite ON DELETE NO ACTION FK
    -- with this SET NULL one does not "vacuously satisfy" the composite check once SET NULL
    -- fires, as MATCH SIMPLE null-exemption might suggest — PostgreSQL evaluates the NO ACTION
    -- check against the row as it stood at delete time and rejects the delete outright, so a
    -- teacher could never delete their own period once any correction request referenced it.
    -- ON DELETE SET NULL here (portable to PostgreSQL 14, unlike the column-specific SET NULL
    -- syntax added in PostgreSQL 15) is what actually lets the delete succeed while nulling the
    -- reference and retaining the request's own history (requestedByTeacherId, teacher names,
    -- reason, timestamps, etc. all survive on the row). The database does NOT itself guarantee
    -- that a request's school_id/academic_session_id match whatever timetable_entry_id used to
    -- point to — TimetableCorrectionService.submit()/review() independently re-validate tenant,
    -- session, and ownership against the live entry on every write, so this is enforced at the
    -- application/service layer, not by a composite foreign key.
    FOREIGN KEY (timetable_entry_id) REFERENCES timetable_entry (id) ON DELETE SET NULL,
    FOREIGN KEY (school_id, requested_by_teacher_id) REFERENCES teacher (school_id, teacher_id),
    FOREIGN KEY (school_id, expected_current_teacher_id) REFERENCES teacher (school_id, teacher_id),
    FOREIGN KEY (school_id, requested_teacher_id) REFERENCES teacher (school_id, teacher_id)
);
CREATE UNIQUE INDEX uq_timetable_correction_pending
    ON timetable_correction_request (school_id, requested_by_teacher_id, timetable_entry_id)
    WHERE status = 'PENDING';
CREATE INDEX idx_timetable_correction_review ON timetable_correction_request (school_id, status, created_at);
