-- SCHEMA-ONLY. No existing rows are updated. Global scripture is intentionally empty.
CREATE TABLE wisdom_thought (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 0,
 school_id bigint REFERENCES school(id), body varchar(300) NOT NULL,
 audience varchar(20) NOT NULL CHECK (audience IN ('EVERYONE','STUDENT','TEACHER','PARENT','ADMIN')),
 active boolean NOT NULL DEFAULT true, CHECK (length(trim(body)) > 0)
);
CREATE INDEX wisdom_thought_school ON wisdom_thought(school_id);
CREATE TABLE wisdom_override (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 0,
 school_id bigint NOT NULL REFERENCES school(id), display_date date NOT NULL,
 audience varchar(20) NOT NULL CHECK (audience IN ('EVERYONE','STUDENT','TEACHER','PARENT','ADMIN')),
 thought_id bigint NOT NULL REFERENCES wisdom_thought(id), UNIQUE(school_id,display_date,audience)
);
CREATE TABLE wisdom_verse (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 0,
 chapter integer NOT NULL CHECK(chapter BETWEEN 1 AND 18), verse integer NOT NULL CHECK(verse > 0),
 sanskrit text NOT NULL, transliteration text NOT NULL, translation text NOT NULL,
 source_name text NOT NULL, source_url text NOT NULL, license text NOT NULL,
 source_version varchar(100) NOT NULL, verified_by varchar(200) NOT NULL,
 verified_at timestamptz NOT NULL, themes text NOT NULL,
 UNIQUE(source_name,source_version,chapter,verse),
 CHECK(length(trim(sanskrit))>0 AND length(trim(transliteration))>0 AND length(trim(translation))>0
 AND length(trim(license))>0 AND length(trim(verified_by))>0)
);
CREATE TABLE wisdom_teaching (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, version bigint NOT NULL DEFAULT 0,
 school_id bigint NOT NULL REFERENCES school(id), verse_id bigint NOT NULL REFERENCES wisdom_verse(id),
 title varchar(160) NOT NULL, simple_meaning text NOT NULL, understanding text NOT NULL, lesson text NOT NULL,
 publication_date date, publish_at timestamptz, publication_zone varchar(64),
 CHECK ((publish_at IS NULL AND publication_date IS NULL AND publication_zone IS NULL)
 OR (publish_at IS NOT NULL AND publication_date IS NOT NULL AND publication_zone IS NOT NULL)),
 UNIQUE(school_id,publication_date)
);
CREATE INDEX wisdom_teaching_publication ON wisdom_teaching(school_id,publish_at DESC);
