-- DATA-MUTATING: insert original Edunexify editorial thoughts only; no existing data updates.
-- Never applied to any persistent/shared environment (confirmed via git history — this file has
-- never been committed) — safe to expand in place rather than layering a follow-up migration.
INSERT INTO wisdom_thought(body,audience,active) VALUES
('A small act of kindness can change the shape of someone’s day.','EVERYONE',true),
('Progress begins with one honest effort.','EVERYONE',true),
('Listen with the same care you hope to receive.','EVERYONE',true),
('Your next step matters more than your last mistake.','EVERYONE',true),
('Patience gives understanding room to grow.','EVERYONE',true),
('Ask a question today that helps you learn something new.','EVERYONE',true),
('Courage can be quiet: try again.','EVERYONE',true),
('Make room for someone who feels left out.','EVERYONE',true),
('Practice turns a difficult beginning into a new ability.','EVERYONE',true),
('Let your actions show the respect your words promise.','EVERYONE',true),
('A calm pause can lead to a wiser choice.','EVERYONE',true),
('Celebrate effort, in yourself and in others.','EVERYONE',true),
('Care for the things you share with others.','EVERYONE',true),
('Being helpful is a strength you can practice every day.','EVERYONE',true),
('A thoughtful word can make a hard day lighter.','EVERYONE',true),
('Learn something, share something, appreciate someone.','EVERYONE',true),
('Give your full attention to one good thing today.','EVERYONE',true),
('You can disagree and still be kind.','EVERYONE',true),
('Responsibility grows when we keep small promises.','EVERYONE',true),
('Be curious enough to look beyond your first answer.','EVERYONE',true),
('Good habits begin with choices small enough to repeat.','EVERYONE',true),
('The work you do with care has value.','EVERYONE',true),
('Let gratitude help you notice what is already good.','EVERYONE',true),
('A fair choice considers the person who has the least say.','EVERYONE',true),
('You do not need to be perfect to make a useful contribution.','EVERYONE',true),
('Take pride in improving, even when nobody is keeping score.','EVERYONE',true),
('A mistake becomes useful when it teaches you something.','EVERYONE',true),
('Respect begins with seeing another person’s effort.','EVERYONE',true),
('Share credit generously and accept responsibility honestly.','EVERYONE',true),
('Leave a little more kindness wherever you go.','EVERYONE',true),
('Rest, reflect, and return with a fresh mind.','EVERYONE',true),
('Honesty is easiest when you practice it in small moments first.','EVERYONE',true),
('Discipline is choosing what you want most over what you want now.','EVERYONE',true),
('A consistent effort beats an occasional burst of brilliance.','EVERYONE',true),
('Service becomes meaningful when you expect nothing back for it.','EVERYONE',true),
('Self-control is a muscle — it grows stronger each time you use it.','EVERYONE',true),
('The way you treat someone who cannot help you says a lot about you.','EVERYONE',true),
('Growth often hides inside the tasks you would rather skip.','EVERYONE',true),
('A humble person can learn from anyone, in any room.','EVERYONE',true),
('Courage is not the absence of fear, but acting well despite it.','EVERYONE',true),
('Keep your word even when it costs you a little comfort.','EVERYONE',true),
('Consistency turns a good intention into a real habit.','EVERYONE',true),
('The most useful skill you can build is finishing what you start.','EVERYONE',true),
('Kindness costs you nothing and often means everything.','EVERYONE',true),
('A good question is worth more than a quick answer.','EVERYONE',true),
('Patience is trusting that good things are still on their way.','EVERYONE',true),
('Say sorry plainly, without turning it into an excuse.','EVERYONE',true),
('Your reputation is built in the moments no one is grading you.','EVERYONE',true),
('Helping quietly is still helping fully.','EVERYONE',true),
('A small habit, repeated daily, becomes a strength for life.','EVERYONE',true),
('Choose honesty even when a small lie would be easier.','EVERYONE',true),
('Responsibility means owning the outcome, not just the intention.','EVERYONE',true),
('Real confidence lets you say, “I do not know yet.”','EVERYONE',true),
('Every skill worth having was once uncomfortable to practice.','EVERYONE',true),
('Treat today’s effort as a gift to your future self.','EVERYONE',true),
('The best apology is changed behavior.','EVERYONE',true),
('Discipline feels heavy at first and light with practice.','EVERYONE',true),
('Notice who is left out, and make room for them.','EVERYONE',true),
('Humility is being teachable, not being small.','EVERYONE',true),
('A calm response can defuse what anger would only inflame.','EVERYONE',true),
('Do the right thing, especially when it is inconvenient.','EVERYONE',true),
('Your attention is valuable — spend it on what truly matters.','EVERYONE',true),
('Perseverance is just patience applied to effort.','EVERYONE',true),
('A promise kept quietly builds more trust than one announced loudly.','EVERYONE',true),
('Respect is offered first, not earned through fear.','EVERYONE',true),
('Gratitude turns “enough” into “plenty.”','EVERYONE',true),
('Small honesty today prevents a big regret tomorrow.','EVERYONE',true),
('The way you practice matters more than how naturally it comes to you.','EVERYONE',true),
('Choosing kindness under pressure is real character.','EVERYONE',true),
('A well-kept promise is a small act of leadership.','EVERYONE',true),
('Curiosity is the beginning of every real skill.','EVERYONE',true),
('Being dependable is a quiet kind of greatness.','EVERYONE',true),
('Every strong habit was once a small, deliberate choice.','EVERYONE',true),
('Kind honesty helps more than comfortable silence.','EVERYONE',true),
('Effort compounds — today’s practice is tomorrow’s ease.','EVERYONE',true),
('Listening fully is a form of respect.','EVERYONE',true),
('The bravest thing you can do today may be trying again.','EVERYONE',true),
('Consistency is choosing the same right thing, day after day.','EVERYONE',true),
('Serve without needing an audience to notice.','EVERYONE',true),
('A steady pace finishes more races than a fast start.','EVERYONE',true),
('Own your mistake before someone else has to point it out.','EVERYONE',true),
('Simple gratitude, spoken aloud, brightens two days — theirs and yours.','EVERYONE',true),
('What you tolerate, you teach others is acceptable.','EVERYONE',true),
('Discipline is remembering what you decided when you are no longer in the mood.','EVERYONE',true),
('A good habit is a promise you keep to yourself.','EVERYONE',true),
('Show respect to people who can do nothing for you.','EVERYONE',true),
('Self-control today is freedom tomorrow.','EVERYONE',true),
('Real strength shows up in ordinary, unnoticed moments.','EVERYONE',true),
('Choose the harder right over the easier wrong.','EVERYONE',true),
('Being trustworthy means your word and your actions match.','EVERYONE',true),
('Practice is repeated honesty with yourself about what still needs work.','EVERYONE',true),
('A patient teacher and a patient student both grow faster.','EVERYONE',true),
('The quality of your effort is a choice, not a mood.','EVERYONE',true),
('Genuine humility asks, “What can I learn here?”','EVERYONE',true),
('Small, steady service adds up to something significant.','EVERYONE',true),
('A mistake in your notebook is cheaper than one in the exam hall — learn from it now.','STUDENT',true),
('Ask your question before the lesson moves on; curiosity does not wait well.','STUDENT',true),
('The student who reviews today’s class today rarely panics before a test.','STUDENT',true),
('Your effort in practice is what shows up on exam day.','STUDENT',true),
('A tidy desk often leads to a tidier mind.','STUDENT',true),
('Helping a classmate understand something helps you understand it twice as well.','STUDENT',true),
('Writing slower and correctly beats writing fast and wrong.','STUDENT',true),
('The subject you find hardest deserves your calmest attention, not your least.','STUDENT',true),
('Raise your hand even when you are not fully sure — that is how sure begins.','STUDENT',true),
('A little revision each evening outweighs a lot of revision the night before.','STUDENT',true),
('Being new at something is the only way to eventually be good at it.','STUDENT',true),
('Your classmates remember who was kind to them more than who scored highest.','STUDENT',true),
('Take care of borrowed books and pencils as if they were your favorite ones.','STUDENT',true),
('A question that feels “silly” is usually one three other students also have.','STUDENT',true),
('The goal of homework is understanding, not just finishing.','STUDENT',true),
('Respect your teacher’s time by listening the first time it is explained.','STUDENT',true),
('Set your bag and books ready the night before, and mornings feel calmer.','STUDENT',true),
('Good marks matter less than the good habits that keep earning them.','STUDENT',true),
('Compete with who you were last term, not just with your classmates.','STUDENT',true),
('A single focused hour beats three distracted ones.','STUDENT',true),
('The way you correct a mistake teaches as much as the lesson itself.','TEACHER',true),
('A patient explanation today saves confusion for the rest of the term.','TEACHER',true),
('Notice the quiet student who never asks for attention.','TEACHER',true),
('Your calm on a chaotic day becomes the classroom’s calm.','TEACHER',true),
('Praise effort as generously as you praise results.','TEACHER',true),
('Every student learns at their own pace — protect the ones who need more time.','TEACHER',true),
('A well-prepared lesson respects your students’ time.','TEACHER',true),
('The way you speak to a struggling student may be the encouragement they remember for years.','TEACHER',true),
('Consistency in your expectations helps students feel safe enough to try.','TEACHER',true),
('Small, specific feedback helps more than a single grade ever could.','TEACHER',true),
('Model the behavior you are asking your class to practice.','TEACHER',true),
('A classroom feels safe when mistakes are treated as part of learning.','TEACHER',true),
('Your patience on a difficult day is invisible work that still matters.','TEACHER',true),
('Listening to a student’s question fully often reveals what they actually need.','TEACHER',true),
('The lesson plan matters less than the relationship that makes it land.','TEACHER',true),
('Celebrate the student who improved quietly, not just the one who excelled loudly.','TEACHER',true),
('A fair teacher is remembered longer than a strict one.','TEACHER',true),
('Your enthusiasm for the subject is often more contagious than the syllabus itself.','TEACHER',true),
('Correct behavior privately; recognize effort publicly.','TEACHER',true),
('The best lesson you teach may not be in today’s subject at all.','TEACHER',true),
('A few minutes of full attention mean more to your child than a full afternoon of distracted presence.','PARENT',true),
('Children repeat what they see far more than what they are told.','PARENT',true),
('Praising effort raises a child more resilient than praising only results.','PARENT',true),
('Ask about their day in a way that invites more than “fine.”','PARENT',true),
('A calm response to a mistake teaches more than a sharp one ever could.','PARENT',true),
('Your child’s teacher is a partner, not an opponent — treat them like one.','PARENT',true),
('Consistency at home gives a child the steadiness to handle change elsewhere.','PARENT',true),
('Let your child struggle with a problem before you hand them the answer.','PARENT',true),
('Bedtime routines built early make for calmer mornings later.','PARENT',true),
('Celebrate the courage to try something new as much as the outcome.','PARENT',true),
('A shared meal without screens says more than a long conversation about screens.','PARENT',true),
('Your patience during homework time teaches patience better than any lecture.','PARENT',true),
('Let mistakes be lessons at home before they become bigger lessons outside it.','PARENT',true),
('Notice effort improving, even when results are still catching up.','PARENT',true),
('A parent’s calm is often the thermostat for the whole household’s mood.','PARENT',true),
('Speak about their teachers and school with respect, even when frustrated.','PARENT',true),
('Small, consistent encouragement outlasts big, occasional praise.','PARENT',true),
('Give your child room to solve small problems — it builds their confidence for bigger ones.','PARENT',true),
('What you model under stress teaches louder than what you say when calm.','PARENT',true),
('A five-minute bedtime chat can reveal what a whole day of questions could not.','PARENT',true);
