CREATE TABLE teacher_substitution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    substitution_date DATE NOT NULL,
    timetable_entry_id BIGINT NOT NULL,
    original_teacher_id VARCHAR(255) NOT NULL,
    original_teacher_name VARCHAR(255) NOT NULL,
    substitute_teacher_id VARCHAR(255) NOT NULL,
    substitute_teacher_name VARCHAR(255) NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    section_name VARCHAR(50),
    subject_name VARCHAR(255) NOT NULL,
    period_number INTEGER NOT NULL,
    start_time VARCHAR(20) NOT NULL,
    end_time VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('ACTIVE', 'CANCELLED')),
    assigned_by VARCHAR(255) NOT NULL,
    assigned_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    FOREIGN KEY (timetable_entry_id) REFERENCES timetable_entry (id)
);

CREATE UNIQUE INDEX uq_teacher_substitution_active_period
    ON teacher_substitution (school_id, substitution_date, timetable_entry_id)
    WHERE status = 'ACTIVE';
CREATE INDEX idx_teacher_substitution_substitute_date
    ON teacher_substitution (school_id, substitute_teacher_id, substitution_date, status);
CREATE INDEX idx_teacher_substitution_period
    ON teacher_substitution (school_id, substitution_date, period_number, status);
