CREATE TABLE support_ticket (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    ticket_number VARCHAR(20),
    school_id BIGINT NOT NULL,
    reporter_user_id VARCHAR(255) NOT NULL,
    reporter_name VARCHAR(255) NOT NULL,
    reporter_role VARCHAR(50) NOT NULL,
    category VARCHAR(30) NOT NULL,
    title VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    screenshot_object_key VARCHAR(500),
    route VARCHAR(500),
    platform VARCHAR(20) NOT NULL CHECK (platform IN ('WEB', 'ANDROID')),
    app_version VARCHAR(50),
    status VARCHAR(20) NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'RESOLVED')),
    internal_note TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX uq_support_ticket_number ON support_ticket (ticket_number);
CREATE INDEX idx_support_ticket_school_status ON support_ticket (school_id, status);
CREATE INDEX idx_support_ticket_reporter ON support_ticket (school_id, reporter_user_id);
CREATE INDEX idx_support_ticket_status_category ON support_ticket (status, category);
