-- Homework & Classwork (Phase 1): a teacher's post for one timetable period on one date.
-- Class/section/subject are snapshots taken from the timetable entry at write time; class and
-- section ids are what student visibility and notification fan-out are resolved against.
CREATE TABLE homework_classwork (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    teacher_id VARCHAR(255) NOT NULL,
    teacher_name VARCHAR(255),
    class_id BIGINT NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    section_id BIGINT,
    section_name VARCHAR(50),
    subject_name VARCHAR(255) NOT NULL,
    timetable_entry_id BIGINT,
    work_date DATE NOT NULL,
    classwork TEXT,
    homework TEXT,
    due_date DATE,
    attachment_object_key VARCHAR(500),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_homework_classwork_has_content CHECK (classwork IS NOT NULL OR homework IS NOT NULL),
    CONSTRAINT ck_homework_classwork_due_after_work CHECK (due_date IS NULL OR due_date >= work_date)
);

-- One post per period per date: a double-tapped submit cannot create two posts (and notify twice).
CREATE UNIQUE INDEX uq_homework_classwork_period_date
    ON homework_classwork (school_id, timetable_entry_id, work_date)
    WHERE timetable_entry_id IS NOT NULL;

-- Student views: their class (and section) by work date / due date.
CREATE INDEX idx_homework_classwork_class_date
    ON homework_classwork (school_id, academic_session_id, class_id, work_date DESC);
CREATE INDEX idx_homework_classwork_class_due
    ON homework_classwork (school_id, academic_session_id, class_id, due_date)
    WHERE due_date IS NOT NULL;

-- Teacher views: their own recent posts.
CREATE INDEX idx_homework_classwork_teacher_date
    ON homework_classwork (school_id, teacher_id, work_date DESC, id DESC);
