-- Homework & Classwork: up to 5 attachments per post (replaces the single attachment column).
CREATE TABLE homework_classwork_attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    homework_classwork_id BIGINT NOT NULL REFERENCES homework_classwork(id) ON DELETE CASCADE,
    object_key VARCHAR(500) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    file_size BIGINT NOT NULL,
    sort_order INT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    -- An uploaded object belongs to exactly one post.
    CONSTRAINT uq_homework_classwork_attachment_object_key UNIQUE (object_key),
    CONSTRAINT ck_homework_classwork_attachment_type
        CHECK (content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')),
    CONSTRAINT ck_homework_classwork_attachment_size CHECK (file_size > 0 AND file_size <= 10485760)
);

CREATE INDEX idx_homework_classwork_attachment_post
    ON homework_classwork_attachment (homework_classwork_id, sort_order);

-- Carry over any existing single attachment. Content type and size come from the verified
-- upload intent when it still exists; otherwise the type is taken from the object key's extension.
INSERT INTO homework_classwork_attachment
    (homework_classwork_id, object_key, file_name, content_type, file_size, sort_order, created_at)
SELECT w.id,
       w.attachment_object_key,
       LEFT(regexp_replace(w.attachment_object_key, '^.*/', ''), 255),
       COALESCE(i.expected_content_type,
                CASE
                    WHEN lower(w.attachment_object_key) LIKE '%.pdf' THEN 'application/pdf'
                    WHEN lower(w.attachment_object_key) LIKE '%.png' THEN 'image/png'
                    WHEN lower(w.attachment_object_key) LIKE '%.webp' THEN 'image/webp'
                    ELSE 'image/jpeg'
                END),
       COALESCE(NULLIF(i.expected_size, 0), 1),
       0,
       w.created_at
FROM homework_classwork w
LEFT JOIN upload_intent i ON i.object_key = w.attachment_object_key
WHERE w.attachment_object_key IS NOT NULL;

ALTER TABLE homework_classwork DROP COLUMN attachment_object_key;
