-- Class Updates (Phase 1): a teacher's academic update for one class/section they teach.
-- Class/section/subject are snapshots taken from the teacher's timetable at write time; class and
-- section ids are what student visibility and notification fan-out are resolved against.
CREATE TABLE class_update (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    teacher_id VARCHAR(255) NOT NULL,
    teacher_name VARCHAR(255),
    class_id BIGINT NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    section_id BIGINT,
    section_name VARCHAR(50),
    subject_name VARCHAR(255),
    title VARCHAR(150) NOT NULL,
    message TEXT NOT NULL,
    -- Optional single attachment. Type and size come from the verified upload intent.
    attachment_object_key VARCHAR(500),
    attachment_file_name VARCHAR(255),
    attachment_content_type VARCHAR(100),
    attachment_file_size BIGINT,
    -- Absolute instant: once passed, the update leaves students' active list.
    expires_at TIMESTAMPTZ,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_class_update_attachment_complete CHECK (
        (attachment_object_key IS NULL AND attachment_file_name IS NULL
            AND attachment_content_type IS NULL AND attachment_file_size IS NULL)
        OR (attachment_object_key IS NOT NULL AND attachment_file_name IS NOT NULL
            AND attachment_content_type IS NOT NULL AND attachment_file_size IS NOT NULL)),
    CONSTRAINT ck_class_update_attachment_type CHECK (attachment_content_type IS NULL
        OR attachment_content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')),
    CONSTRAINT ck_class_update_attachment_size CHECK (attachment_file_size IS NULL
        OR (attachment_file_size > 0 AND attachment_file_size <= 10485760))
);

-- An uploaded object belongs to exactly one update.
CREATE UNIQUE INDEX uq_class_update_attachment_object_key
    ON class_update (attachment_object_key)
    WHERE attachment_object_key IS NOT NULL;

-- Student views: their class (and section), newest first.
CREATE INDEX idx_class_update_class_created
    ON class_update (school_id, academic_session_id, class_id, created_at DESC);

-- Teacher views: their own recent updates.
CREATE INDEX idx_class_update_teacher_created
    ON class_update (school_id, teacher_id, created_at DESC, id DESC);
