-- Exam & Assessment Calendar (Phase 1): a scheduled assessment for one class (optionally one
-- section) and subject in the school's current session. Class/section names are snapshots; the
-- ids are what student visibility and notification fan-out are resolved against.
CREATE TABLE assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    created_by_user_id VARCHAR(255) NOT NULL,
    created_by_role VARCHAR(20) NOT NULL CHECK (created_by_role IN ('TEACHER', 'ADMIN')),
    created_by_name VARCHAR(255),
    assessment_type VARCHAR(30) NOT NULL CHECK (assessment_type IN
        ('CLASS_TEST', 'UNIT_TEST', 'PRACTICAL', 'PRE_BOARD', 'INTERNAL_ASSESSMENT', 'OTHER')),
    class_id BIGINT NOT NULL,
    class_name VARCHAR(255) NOT NULL,
    section_id BIGINT,
    section_name VARCHAR(50),
    subject_name VARCHAR(255) NOT NULL,
    title VARCHAR(150) NOT NULL,
    assessment_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    syllabus TEXT NOT NULL,
    instructions TEXT,
    -- Optional single attachment. Type and size come from the verified upload intent.
    attachment_object_key VARCHAR(500),
    attachment_file_name VARCHAR(255),
    attachment_content_type VARCHAR(100),
    attachment_file_size BIGINT,
    -- Set once the day-before reminder has been published (reset when the date changes).
    reminder_sent_at TIMESTAMPTZ,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT ck_assessment_end_needs_start CHECK (end_time IS NULL OR start_time IS NOT NULL),
    CONSTRAINT ck_assessment_end_after_start CHECK (end_time IS NULL OR end_time > start_time),
    CONSTRAINT ck_assessment_attachment_complete CHECK (
        (attachment_object_key IS NULL AND attachment_file_name IS NULL
            AND attachment_content_type IS NULL AND attachment_file_size IS NULL)
        OR (attachment_object_key IS NOT NULL AND attachment_file_name IS NOT NULL
            AND attachment_content_type IS NOT NULL AND attachment_file_size IS NOT NULL)),
    CONSTRAINT ck_assessment_attachment_type CHECK (attachment_content_type IS NULL
        OR attachment_content_type IN ('image/jpeg', 'image/png', 'image/webp', 'application/pdf')),
    CONSTRAINT ck_assessment_attachment_size CHECK (attachment_file_size IS NULL
        OR (attachment_file_size > 0 AND attachment_file_size <= 10485760))
);

-- An uploaded object belongs to exactly one assessment.
CREATE UNIQUE INDEX uq_assessment_attachment_object_key
    ON assessment (attachment_object_key)
    WHERE attachment_object_key IS NOT NULL;

-- Student views: their class (and section) by date.
CREATE INDEX idx_assessment_class_date
    ON assessment (school_id, academic_session_id, class_id, assessment_date);

-- Teacher views: their own assessments by date.
CREATE INDEX idx_assessment_creator_date
    ON assessment (school_id, created_by_user_id, assessment_date);

-- Reminder scan: assessments on a given date not yet reminded.
CREATE INDEX idx_assessment_reminder_due
    ON assessment (assessment_date)
    WHERE reminder_sent_at IS NULL;
