-- Student Attendance V2: an explicit attendance model replacing the legacy absence-only ledger.
--
-- attendance_session: one row per submitted class (section) day — "attendance was taken for this
-- class/section on this date". student_attendance: one explicit PRESENT/ABSENT row per eligible
-- student of that submission (no sentinel rows, no "missing row means present").
-- absence_charge_settlement: the unapplied-absence fee's payment state, kept out of attendance.

CREATE TABLE attendance_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    school_id BIGINT NOT NULL,
    academic_session_id BIGINT NOT NULL,
    class_id BIGINT NOT NULL,
    section_id BIGINT,
    attendance_date DATE NOT NULL,
    marked_by_user_id VARCHAR(255) NOT NULL,
    marked_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

-- One submission per school + session + class + section + date. section_id is NULL for a class
-- without sections, so the two cases get separate partial unique indexes (NULLs never collide in
-- a plain unique index).
CREATE UNIQUE INDEX uq_attendance_session_section_day
    ON attendance_session (school_id, academic_session_id, class_id, section_id, attendance_date)
    WHERE section_id IS NOT NULL;
CREATE UNIQUE INDEX uq_attendance_session_class_day
    ON attendance_session (school_id, academic_session_id, class_id, attendance_date)
    WHERE section_id IS NULL;

-- School-wide by date (dashboards, absence emails, date-range summaries).
CREATE INDEX idx_attendance_session_school_date
    ON attendance_session (school_id, attendance_date);
-- A class's submissions over a date range (class summaries, consecutive absences, trends).
CREATE INDEX idx_attendance_session_class_date
    ON attendance_session (school_id, class_id, attendance_date);

CREATE TABLE student_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revision BIGINT NOT NULL DEFAULT 0,
    attendance_session_id BIGINT NOT NULL REFERENCES attendance_session(id) ON DELETE CASCADE,
    student_id VARCHAR(255) NOT NULL,
    status VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT uq_student_attendance_session_student UNIQUE (attendance_session_id, student_id),
    CONSTRAINT ck_student_attendance_status CHECK (status IN ('PRESENT', 'ABSENT'))
);

-- A student's own history (joined to attendance_session for school/date filtering).
CREATE INDEX idx_student_attendance_student
    ON student_attendance (student_id, attendance_session_id);
-- Counting/filtering a submission's rows by status.
CREATE INDEX idx_student_attendance_session_status
    ON student_attendance (attendance_session_id, status);

-- Fee for an absence without an approved leave (see AbsenceChargeService): a chargeable absence
-- is settled once a fee payment covers it. The row disappears with the attendance row.
CREATE TABLE absence_charge_settlement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school_id BIGINT NOT NULL,
    student_attendance_id BIGINT NOT NULL REFERENCES student_attendance(id) ON DELETE CASCADE,
    settled_at TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_absence_charge_settlement_attendance UNIQUE (student_attendance_id)
);
