name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~/EduPay-Leave-backend
            git pull origin main

            docker stop ias-backend-container || true
            docker rm ias-backend-container || true

            docker build -t ias-backend .

            docker run -d \
              --restart unless-stopped \
              --log-driver json-file \
              --log-opt max-size=10m \
              --log-opt max-file=3 \
              --health-cmd="curl --fail http://localhost:8080/actuator/health || exit 1" \
              --health-interval=30s \
              --health-timeout=5s \
              --health-retries=3 \
              --name ias-backend-container \
              -p 127.0.0.1:8080:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATASOURCE_URL='${{ secrets.DB_URL }}' \
              -e SPRING_DATASOURCE_USERNAME='${{ secrets.DB_USERNAME }}' \
              -e SPRING_DATASOURCE_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e SPRING_MAIL_PASSWORD='${{ secrets.MAIL_PASSWORD }}' \
              -e JWT_PRIVATE_KEY='${{ secrets.JWT_PRIVATE_KEY }}' \
              -e JWT_PUBLIC_KEY='${{ secrets.JWT_PUBLIC_KEY }}' \
              -e FRONTEND_URL='${{ secrets.DB_URL }}' \
              ias-backend
