name: Stop Backend

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Stop Backend Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker stop ias-backend-container || true