package com.indraacademy.ias_management.service;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.indraacademy.ias_management.entity.Leave;
import com.indraacademy.ias_management.entity.LeaveStatus;
import com.indraacademy.ias_management.exception.InvalidLeaveStatusTransitionException;
import com.indraacademy.ias_management.repository.LeaveRepository;
import com.indraacademy.ias_management.util.SecurityUtil;
import jakarta.servlet.http.HttpServletRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.test.util.ReflectionTestUtils;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Covers updateLeaveStatus's hardening: the locked read and the same-status guard.
 *
 * <p>The rule under test is deliberately narrower than "a decided leave is final" — the product
 * has a real, existing reversal feature (APPROVED ↔ REJECTED, ViewLeavesComponent.editLeaveStatus)
 * that this must not break. What's blocked is only a request whose target already matches the
 * leave's current status — a repeat, not a reversal.
 */
@ExtendWith(MockitoExtension.class)
class LeaveServiceTest {

    @Mock private LeaveRepository leaveRepository;
    @Mock private NotificationService notificationService;
    @Mock private AuditService auditService;
    @Mock private SecurityUtil securityUtil;
    @Mock private HttpServletRequest request;

    private LeaveService service;

    private static final Long SCHOOL_ID = 2L;
    private static final Long LEAVE_ID = 1L;

    @BeforeEach
    void setUp() {
        service = new LeaveService();
        ReflectionTestUtils.setField(service, "leaveRepository", leaveRepository);
        ReflectionTestUtils.setField(service, "notificationService", notificationService);
        ReflectionTestUtils.setField(service, "auditService", auditService);
        ReflectionTestUtils.setField(service, "securityUtil", securityUtil);
        ReflectionTestUtils.setField(service, "objectMapper", new ObjectMapper());
        lenient().when(securityUtil.getSchoolId()).thenReturn(SCHOOL_ID);
        lenient().when(securityUtil.getUsername()).thenReturn("tester");
        lenient().when(securityUtil.getRole()).thenReturn("ADMIN");
    }

    private Leave leave(LeaveStatus status) {
        Leave l = new Leave();
        l.setId(LEAVE_ID);
        l.setSchoolId(SCHOOL_ID);
        l.setStudentId("S1");
        l.setStudentName("Test Student");
        l.setLeaveDate("2026-08-20");
        l.setClassName("10");
        l.setReason("Test reason");
        l.setStatus(status);
        return l;
    }

    @Test
    void pendingToApproved_succeeds_theOrdinaryFirstDecision() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.PENDING)));
        when(leaveRepository.save(any(Leave.class))).thenAnswer(inv -> inv.getArgument(0));

        Leave updated = service.updateLeaveStatus(LEAVE_ID, LeaveStatus.APPROVED, request);

        assertThat(updated.getStatus()).isEqualTo(LeaveStatus.APPROVED);
        verify(notificationService).createAutoGeneratedIndividualNotification(
                anyString(), anyString(), eq("Leave_Status_APPROVED"), anyString(), anyString(), anyString());
    }

    @Test
    void pendingToRejected_succeeds_theOrdinaryFirstDecision() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.PENDING)));
        when(leaveRepository.save(any(Leave.class))).thenAnswer(inv -> inv.getArgument(0));

        Leave updated = service.updateLeaveStatus(LEAVE_ID, LeaveStatus.REJECTED, request);

        assertThat(updated.getStatus()).isEqualTo(LeaveStatus.REJECTED);
    }

    /** The double-click / retried-request / "two people approved the same leave" case. */
    @Test
    void reapprovingAnAlreadyApprovedLeave_isRejected_asARepeat() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.APPROVED)));

        assertThatThrownBy(() -> service.updateLeaveStatus(LEAVE_ID, LeaveStatus.APPROVED, request))
                .isInstanceOf(InvalidLeaveStatusTransitionException.class)
                .hasMessageContaining("already")
                .hasMessageContaining("APPROVED");

        verify(leaveRepository, never()).save(any());
        verifyNoInteractions(notificationService);
    }

    @Test
    void rerejectingAnAlreadyRejectedLeave_isRejected_asARepeat() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.REJECTED)));

        assertThatThrownBy(() -> service.updateLeaveStatus(LEAVE_ID, LeaveStatus.REJECTED, request))
                .isInstanceOf(InvalidLeaveStatusTransitionException.class);

        verify(leaveRepository, never()).save(any());
    }

    /** The existing product feature (ViewLeavesComponent.editLeaveStatus) — must keep working. */
    @Test
    void approvedToRejected_stillSucceeds_theExistingReversalFeature() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.APPROVED)));
        when(leaveRepository.save(any(Leave.class))).thenAnswer(inv -> inv.getArgument(0));

        Leave updated = service.updateLeaveStatus(LEAVE_ID, LeaveStatus.REJECTED, request);

        assertThat(updated.getStatus()).isEqualTo(LeaveStatus.REJECTED);
    }

    @Test
    void rejectedToApproved_stillSucceeds_theExistingReversalFeature() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.REJECTED)));
        when(leaveRepository.save(any(Leave.class))).thenAnswer(inv -> inv.getArgument(0));

        Leave updated = service.updateLeaveStatus(LEAVE_ID, LeaveStatus.APPROVED, request);

        assertThat(updated.getStatus()).isEqualTo(LeaveStatus.APPROVED);
    }

    @Test
    void usesTheLockedFinder_notThePlainFindById() {
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(leave(LeaveStatus.PENDING)));
        when(leaveRepository.save(any(Leave.class))).thenAnswer(inv -> inv.getArgument(0));

        service.updateLeaveStatus(LEAVE_ID, LeaveStatus.APPROVED, request);

        verify(leaveRepository).findByIdForUpdate(LEAVE_ID);
        verify(leaveRepository, never()).findById(any());
    }

    @Test
    void tenantMismatch_stillRejectedBeforeTheStatusCheck_unaffectedByThisChange() {
        Leave otherSchoolLeave = leave(LeaveStatus.PENDING);
        otherSchoolLeave.setSchoolId(999L);
        when(leaveRepository.findByIdForUpdate(LEAVE_ID)).thenReturn(Optional.of(otherSchoolLeave));

        assertThatThrownBy(() -> service.updateLeaveStatus(LEAVE_ID, LeaveStatus.APPROVED, request))
                .isInstanceOf(SecurityException.class);

        verify(leaveRepository, never()).save(any());
    }
}
